openapi: 3.2.0
info:
  contact:
    email: support@instana.com
    name: © Instana
    url: http://instana.com
  termsOfService: https://www.instana.com/terms-of-use/
  title: Instana REST API documentation Service Levels…
  version: 1.307.1417
  x-ibm-ahub-try: true
  x-logo:
    altText: instana logo
    backgroundColor: '#FAFBFC'
    url: header-logo.svg
  description: Searching for answers and best pratices?
servers:
- description: Instana Backend
  url: https://{unit}-{tenant}.instana.io
  variables:
    tenant:
      default: tenant
      description: Customer tenant unit
    unit:
      default: unit
      description: Customer tenant name
- description: Instana Self-Hosted Backend
  url: https://{domain}
  variables:
    domain:
      default: example.com
      description: Customer Self-Hosted domain
tags:
- name: Service Levels Objective(SLO) Configurations
paths:
  /api/settings/slo:
    get:
      operationId: getAllSloConfigs
      parameters:
      - in: query
        name: pageSize
        schema:
          type: integer
          format: int32
          description: Size of the Page
          example: 1
      - in: query
        name: page
        schema:
          type: integer
          format: int32
          description: Page Number
          example: 1
      - in: query
        name: orderBy
        schema:
          type: string
          description: Order By Value
          enum:
          - name
          - entityType
          - entityName
          - blueprint
          - sloStatus
          - sloWindowRemain
          - timeWindow
          - 'null'
          example: name
      - in: query
        name: orderDirection
        schema:
          type: string
          description: Order Direction of the Result, it could be ascending or descending
          enum:
          - ASC
          - DESC
          example: ASC
      - in: query
        name: query
        schema:
          type: string
          description: Keyword or Query which needs to be searched
          example: test SLO
      - in: query
        name: tag
        schema:
          type: array
          description: List of tags which needs to be searched
          example: Testing
          items:
            type: string
            description: List of tags which needs to be searched
            example: Testing
          uniqueItems: true
      - in: query
        name: entityType
        schema:
          type: array
          description: SLO Entity Type which needs to be filtered. (This filter could occurs multiple times.)
          example: application
          items:
            type: string
            description: SLO Entity Type which needs to be filtered. (This filter could occurs multiple times.)
            enum:
            - application
            - website
            - synthetic
            - infrastructure
            example: application
          uniqueItems: true
      - in: query
        name: blueprint
        schema:
          type: array
          description: SLO blueprint Type which needs to be filtered. (This filter could occurs multiple times.)
          example: latency
          items:
            type: string
            description: SLO blueprint Type which needs to be filtered. (This filter could occurs multiple times.)
            enum:
            - latency
            - availability
            - traffic
            - saturation
            - custom
            example: latency
          uniqueItems: true
      - in: query
        name: sloIds
        schema:
          type: array
          description: List of SLO IDs for which details need to be fetched
          example: SLOdCTspkHlS_OzNOATQWgsuw
          items:
            type: string
            description: List of SLO IDs for which details need to be fetched
            example: SLOdCTspkHlS_OzNOATQWgsuw
      - in: query
        name: sloStatus
        schema:
          type: string
          description: Filter by the SLO status
          example: green
      - in: query
        name: entityIds
        schema:
          type: array
          description: List of entity IDs for which details need to be fetched
          example: adsewby312sdfd1
          items:
            type: string
            description: List of entity IDs for which details need to be fetched
            example: adsewby312sdfd1
      - in: query
        name: grouped
        schema:
          type: boolean
          description: Boolean operator which specifies if the results are grouped
          example: false
      - in: query
        name: refresh
        schema:
          type: boolean
          description: Boolean operator which specifies if the cache needs to be refreshed
          example: false
      responses:
        '200':
          content:
            application/json:
              example:
                items:
                - id: SLOY2KDCFExTvmsLyf4W067JQ
                  name: Stans test SLO 2
                  target: 0.99
                  lastUpdated: 1680182215442
                  entity:
                    type: application
                    applicationId: VTNvC_sATZqMj4vSZfsjKA
                    serviceId: null
                    endpointId: null
                    boundaryScope: INBOUND
                    includeInternal: false
                    includeSynthetic: false
                    tagFilterExpression: null
                  rbacTags:
                  - id: R3_hPrHXSMe0yGsnlFdReA
                    displayName: team 1
                  indicator:
                    type: timeBased
                    blueprint: latency
                    threshold: 100
                    aggregation: P90
                  timeWindow:
                    type: rolling
                    duration: 1
                    durationUnit: week
                  tags:
                  - Stan
                  - testing
                - id: SLOsmbQLI8ORcuhF_L-QquFWQ
                  name: '[Should match no nothing test] website entity tag filter'
                  target: 0.9999
                  lastUpdated: 1683792839372
                  rbacTags:
                  - id: R3_hPrHXSMe0yGsnlFdReA
                    displayName: team 1
                  entity:
                    type: website
                    websiteId: XIZGGVT1TX2O-0OFeT2Yig
                    beaconType: httpRequest
                    tagFilterExpression:
                      type: TAG_FILTER
                      name: beacon.geo.country
                      stringValue: Moon
                      numberValue: null
                      booleanValue: null
                      key: null
                      value: Moon
                      operator: EQUALS
                      entity: NOT_APPLICABLE
                  indicator:
                    type: eventBased
                    blueprint: latency
                    threshold: 60000
                  timeWindow:
                    type: rolling
                    duration: 1
                    durationUnit: week
                  tags:
                  - test
                  - no matches
                page: 1
                pageSize: 10000
                totalHits: 2
              schema:
                $ref: '#/components/schemas/PaginatedResult'
          description: Fetched list of the SLO Configurations Successfully
      security:
      - ApiKeyAuth:
        - Default
      summary: Get All SLO Configs
      tags:
      - Service Levels Objective(SLO) Configurations
      x-ibm-ahub-byok: true
    post:
      operationId: createSloConfig
      requestBody:
        content:
          application/json:
            example:
              name: Stans test SLO 4
              target: 0.99
              rbacTags:
              - id: R3_hPrHXSMe0yGsnlFdReA
                displayName: team 1
              entity:
                type: application
                applicationId: VTNvC_sATZqMj4vSZfsjKA
                serviceId: null
                endpointId: null
                boundaryScope: INBOUND
                includeInternal: false
                includeSynthetic: false
                tagFilterExpression: null
              indicator:
                type: timeBased
                blueprint: latency
                threshold: 100
                aggregation: P90
              timeWindow:
                type: rolling
                duration: 1
                durationUnit: week
              tags:
              - Stan
              - testing
            schema:
              $ref: '#/components/schemas/SLOConfigWithRBACTag'
        required: true
      responses:
        '200':
          content:
            application/json:
              example:
                id: SLOdCTspkHlS_OzNOATQWgsuw
                rbacTags:
                - id: R3_hPrHXSMe0yGsnlFdReA
                  displayName: team 1
                createdDate: 1680182236227
                name: Stans test SLO 4
                target: 0.99
                lastUpdated: 1713873207738
                entity:
                  type: application
                  applicationId: VTNvC_sATZqMj4vSZfsjKA
                  serviceId: null
                  endpointId: null
                  boundaryScope: INBOUND
                  includeInternal: false
                  includeSynthetic: false
                  tagFilterExpression: null
                indicator:
                  type: timeBased
                  blueprint: latency
                  threshold: 100
                  aggregation: P90
                timeWindow:
                  type: rolling
                  duration: 1
                  durationUnit: week
                tags:
                - Stan
                - testing
              schema:
                $ref: '#/components/schemas/SLOConfigWithRBACTag'
          description: New SLO Configuration Created Successfully
        '400':
          content:
            application/json:
              example: '{"errors":["Unknown tag filter: call.error"]}'
              schema:
                type: string
          description: Invalid Tag Filter
      security:
      - ApiKeyAuth:
        - canConfigureServiceLevels
      summary: Create a new SLO Config
      tags:
      - Service Levels Objective(SLO) Configurations
      x-ibm-ahub-byok: true
  /api/settings/slo/tags:
    get:
      operationId: getAllSloConfigTags
      parameters:
      - in: query
        name: query
        schema:
          type: string
          description: Keyword or Query which needs to be searched
          example: test SLO
      - in: query
        name: tag
        schema:
          type: array
          description: List of tags which needs to be searched
          example: Testing
          items:
            type: string
            description: List of tags which needs to be searched
            example: Testing
          uniqueItems: true
      - in: query
        name: entityType
        schema:
          type: string
          description: SLO Entity Type which needs to be filtered
          enum:
          - application
          - website
          - synthetic
          - infrastructure
          example: application
      responses:
        '200':
          content:
            application/json:
              example:
              - andre
              - test
              - testing
              - drinks
              - got no snacks
              - timeBased
              - Stan
              - no matches
              - availability
              - Lab
              - demo
              - thiemo
              - TimeWindow Test
              - robot-shop
              - eventBased
              - got snacks
              - migration
              - robert-creates-a-new-sli
              schema:
                type: array
                items:
                  type: string
          description: Fetched list of SLO Configuration tags Successfully
      security:
      - ApiKeyAuth:
        - Default
      summary: Get All SLO Config tags
      tags:
      - Service Levels Objective(SLO) Configurations
      x-ibm-ahub-byok: true
  /api/settings/slo/{id}:
    delete:
      operationId: deleteSloConfig
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
          description: Service Levels Objective Configuration ID
          example: SLOdCTspkHlS_OzNOATQWgsuw
      responses:
        '204':
          description: SLO Configuration Deleted Successfully
      security:
      - ApiKeyAuth:
        - canConfigureServiceLevels
      summary: Delete an existing SLO Config
      tags:
      - Service Levels Objective(SLO) Configurations
      x-ibm-ahub-byok: true
    get:
      operationId: getSloConfigById
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
          description: Service Levels Objective Configuration ID
          example: SLOdCTspkHlS_OzNOATQWgsuw
      - in: query
        name: refresh
        schema:
          type: boolean
          description: Boolean operator which specifies if the cache needs to be refreshed
          example: false
      responses:
        '200':
          content:
            application/json:
              example:
                id: SLOdCTspkHlS_OzNOATQWgsuw
                rbacTags:
                - id: R3_hPrHXSMe0yGsnlFdReA
                  displayName: team 1
                createdDate: 1680182236227
                name: Stans test SLO 4
                target: 0.99
                lastUpdated: 1713873207738
                entity:
                  type: application
                  applicationId: VTNvC_sATZqMj4vSZfsjKA
                  serviceId: null
                  endpointId: null
                  boundaryScope: INBOUND
                  includeInternal: false
                  includeSynthetic: false
                  tagFilterExpression: null
                indicator:
                  type: timeBased
                  blueprint: latency
                  threshold: 100
                  aggregation: P90
                timeWindow:
                  type: rolling
                  duration: 1
                  durationUnit: week
                tags:
                - Stan
                - testing
              schema:
                $ref: '#/components/schemas/SLOConfigWithRBACTag'
          description: Fetched SLO Configuration Successfully
        '404':
          content:
            application/json:
              example:
                errors:
                - The sloConfiguration you are looking for does not exist.
              schema:
                type: string
          description: SLO Configuration Not Found
      security:
      - ApiKeyAuth:
        - Default
      summary: Get an existing SLO Config
      tags:
      - Service Levels Objective(SLO) Configurations
      x-ibm-ahub-byok: true
    put:
      operationId: updateSloConfig
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
          description: Service Levels Objective Configuration ID
          example: SLOdCTspkHlS_OzNOATQWgsuw
      requestBody:
        content:
          application/json:
            example:
              name: Stans test SLO 4
              target: 0.99
              rbacTags:
              - id: R3_hPrHXSMe0yGsnlFdReA
                displayName: team 1
              entity:
                type: application
                applicationId: VTNvC_sATZqMj4vSZfsjKA
                serviceId: null
                endpointId: null
                boundaryScope: INBOUND
                includeInternal: false
                includeSynthetic: false
                tagFilterExpression: null
              indicator:
                type: timeBased
                blueprint: latency
                threshold: 100
                aggregation: P90
              timeWindow:
                type: rolling
                duration: 1
                durationUnit: week
              tags:
              - Stan
              - testing
            schema:
              $ref: '#/components/schemas/SLOConfigWithRBACTag'
        required: true
      responses:
        '200':
          content:
            application/json:
              example:
                id: SLOdCTspkHlS_OzNOATQWgsuw
                rbacTags:
                - id: R3_hPrHXSMe0yGsnlFdReA
                  displayName: team 1
                createdDate: 1680182236227
                name: Stans test SLO 4
                target: 0.99
                lastUpdated: 1713873207738
                entity:
                  type: application
                  applicationId: VTNvC_sATZqMj4vSZfsjKA
                  serviceId: null
                  endpointId: null
                  boundaryScope: INBOUND
                  includeInternal: false
                  includeSynthetic: false
                  tagFilterExpression: null
                indicator:
                  type: timeBased
                  blueprint: latency
                  threshold: 100
                  aggregation: P90
                timeWindow:
                  type: rolling
                  duration: 1
                  durationUnit: week
                tags:
                - Stan
                - testing
              schema:
                $ref: '#/components/schemas/SLOConfigWithRBACTag'
          description: Updated SLO Configuration Successfully
        '400':
          content:
            application/json:
              example:
                errors:
                - 'SloConfiguration with id: GC8r6gbZT4WIhtsMx_YgLg was not found'
              schema:
                type: string
          description: Bad Request
      security:
      - ApiKeyAuth:
        - canConfigureServiceLevels
      summary: Update an existing SLO Config
      tags:
      - Service Levels Objective(SLO) Configurations
      x-ibm-ahub-byok: true
components:
  schemas:
    PaginatedResult:
      type: object
      properties:
        items:
          type: array
          items:
            type: object
        page:
          type: integer
          format: int32
          description: Page Number
          minimum: 1
        pageSize:
          type: integer
          format: int32
          minimum: 1
        totalHits:
          type: integer
          format: int64
          minimum: 0
      required:
      - items
    TagFilterExpressionElement:
      type: object
      description: Boolean expression of tag filters to define the scope of relevant calls.
      discriminator:
        mapping:
          EXPRESSION: '#/components/schemas/TagFilterExpression'
          TAG_FILTER: '#/components/schemas/TagFilter'
        propertyName: type
      properties:
        type:
          type: string
      required:
      - type
    SLOConfigWithRBACTag:
      type: object
      properties:
        createdDate:
          type: string
          format: date-time
          description: Created date of Service Levels Objective Configuration
        entity:
          $ref: '#/components/schemas/SloEntity'
        id:
          type: string
          description: Service Levels Objective Configuration ID
          maxLength: 64
          minLength: 0
        indicator:
          $ref: '#/components/schemas/ServiceLevelIndicator'
        lastUpdated:
          type: string
          format: date-time
          description: Last updated date of Service Levels Objective Configuration
        name:
          type: string
          description: Name of the Service Levels Objective Configuration
        rbacTags:
          type: array
          items:
            $ref: '#/components/schemas/ApiTag'
          uniqueItems: true
        tags:
          type: array
          description: List of tags associated with Service Levels Objective Configuration
          items:
            type: string
            description: List of tags associated with Service Levels Objective Configuration
        target:
          type: number
          format: double
          description: Service Levels Objective Configuration Target
          maximum: 0.9999
          exclusiveMinimum: 0
        timeWindow:
          $ref: '#/components/schemas/TimeWindow'
      required:
      - entity
      - indicator
      - name
      - tags
      - target
      - timeWindow
    ApiTag:
      type: object
      properties:
        displayName:
          type: string
          maxLength: 256
          minLength: 0
        id:
          type: string
          maxLength: 64
          minLength: 0
      required:
      - displayName
      - id
    ServiceLevelIndicator:
      type: object
      description: Indicator of the Service Levels Objective Configuration, it indicates the type of metric by which the SLO should be evaluated
      discriminator:
        mapping:
          availability: '#/components/schemas/AvailabilityBlueprintIndicator'
          custom: '#/components/schemas/CustomBlueprintIndicator'
          latency: '#/components/schemas/LatencyBlueprintIndicator'
          saturation: '#/components/schemas/SaturationBlueprintIndicator'
          traffic: '#/components/schemas/TrafficBlueprintIndicator'
        propertyName: blueprint
      properties:
        aggregation:
          type: string
          description: Aggregation Type for the Threshold Value
          enum:
          - SUM
          - MEAN
          - MAX
          - MIN
          - P25
          - P50
          - P75
          - P90
          - P95
          - P98
          - P99
          - P99_9
          - P99_99
          - DISTINCT_COUNT
          - SUM_POSITIVE
          - PER_SECOND
          - INCREASE
        blueprint:
          type: string
          enum:
          - latency
          - availability
          - traffic
          - saturation
          - custom
        operator:
          type: string
          description: Operator for the Threshold Value
          enum:
          - '>'
          - '>='
          - <
          - <=
        serviceLevelsMeasurement:
          type: string
          description: Defines Measurement Type of SLO
          enum:
          - eventBased
          - timeBased
          - erroneous
          - all
        threshold:
          type: number
          format: double
          description: Threshold Value for the Blueprint
        type:
          type: string
          enum:
          - eventBased
          - timeBased
    TimeWindow:
      type: object
      description: Time Window type of the SLO, it could be Fixed or Rolling
      discriminator:
        mapping:
          fixed: '#/components/schemas/FixedTimeWindow'
          rolling: '#/components/schemas/RollingTimeWindow'
        propertyName: type
      properties:
        duration:
          type: integer
          format: int32
          description: Duration of the Time Window
        durationUnit:
          type: string
          description: Unit of the Time Window Duration
          enum:
          - millisecond
          - second
          - minute
          - hour
          - day
          - week
          - month
        timezone:
          type: string
          description: Timezone string
        type:
          type: string
      required:
      - duration
      - durationUnit
      - type
    SloEntity:
      type: object
      description: Entity of the Service Levels Objective Configuration, it could be either Application nor Website
      discriminator:
        mapping:
          application: '#/components/schemas/ApplicationSloEntity'
          infrastructure: '#/components/schemas/InfraSloEntity'
          synthetic: '#/components/schemas/SyntheticSloEntity'
          website: '#/components/schemas/WebsiteSloEntity'
        propertyName: type
      properties:
        tagFilterExpression:
          $ref: '#/components/schemas/TagFilterExpressionElement'
        type:
          type: string
      required:
      - type
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: authorization
      type: apiKey
      description: "## Example\n\n```bash\ncurl --request GET \\\n  --url https://test-instana.instana.io/api/application-monitoring/catalog/metrics \\\n  --header 'authorization: apiToken xxxxxxxxxxxxxxxx'\n```\n"
x-tagGroups:
- name: Websites & Mobile Apps
  tags:
  - Website Metrics
  - Website Catalog
  - Website Analyze
  - Website Configuration
  - Mobile App Metrics
  - Mobile App Catalog
  - Mobile App Analyze
  - Mobile App Configuration
  - End User Monitoring
- name: Applications
  tags:
  - Application Metrics
  - Application Resources
  - Application Catalog
  - Application Analyze
  - Application Settings
  - Application Topology
  - Application Alert Configuration
  - Global Application Alert Configuration
- name: Infrastructure
  tags:
  - Infrastructure Analyze
  - Infrastructure Metrics
  - Infrastructure Resources
  - Infrastructure Catalog
  - Infrastructure Topology
- name: Logging
  tags:
  - Logging Analyze
- name: Synthetic Monitoring
  tags:
  - Synthetic Catalog
  - Synthetic Metrics
  - Synthetic Settings
  - Synthetic Test Playback Results
  - Synthetic Alert Configuration
- name: Logs
  tags:
  - Log Alert Configuration
- name: Events
  tags:
  - Events
  - Event Settings
- name: Automation
  tags:
  - Action Catalog
  - Action History
  - Policies
- name: Service Levels
  tags:
  - SLI Settings
  - SLI Report
  - Apdex Settings
  - Apdex Report
  - Service Levels Objective(SLO) Configurations
  - Service Levels Objective(SLO) Report
  - Service Levels Alert Configuration
  - SLO Correction Configurations
  - SLO Correction Windows
- name: AI Management
  tags:
  - AI Management
- name: Settings
  tags:
  - Custom Dashboards
  - User
  - Groups
  - Teams
  - Roles
  - Audit Log
  - API Token
  - Maintenance Configuration
  - Synthetic Calls
  - Session Settings
  - Automation Settings
  - Authentication
- name: Open Beta Features
  tags:
  - Infrastructure Analyze
- name: Closed Beta Features
  tags:
  - Infrastructure Alert Configuration
- name: Instana
  tags:
  - Releases
  - Host Agent
  - Health
  - Usage
