openapi: 3.2.0
info:
  contact:
    email: support@instana.com
    name: © Instana
    url: http://instana.com
  termsOfService: https://www.instana.com/terms-of-use/
  title: Instana REST API documentation SLI Settings API
  version: 1.307.1417
  x-ibm-ahub-try: true
  x-logo:
    altText: instana logo
    backgroundColor: '#FAFBFC'
    url: header-logo.svg
  description: Searching for answers and best pratices?
servers:
- description: Instana Backend
  url: https://{unit}-{tenant}.instana.io
  variables:
    tenant:
      default: tenant
      description: Customer tenant unit
    unit:
      default: unit
      description: Customer tenant name
- description: Instana Self-Hosted Backend
  url: https://{domain}
  variables:
    domain:
      default: example.com
      description: Customer Self-Hosted domain
tags:
- name: SLI Settings
  description: '## Deprecated Parameters

    **tagFilters** The list of tag filters. It is replaced by **tagFilterExpression**'
paths:
  /api/settings/sli:
    get:
      deprecated: true
      operationId: getAllSliConfigs
      responses:
        '200':
          content:
            application/json:
              example:
                id: 3J0RDgfyQz-P_hVzbNNb4A
                sliName: test-application-sli
                initialEvaluationTimestamp: 1732017600000
                metricConfiguration:
                  metricName: latency
                  metricAggregation: P90
                  threshold: 555
                sliEntity:
                  sliType: application
                  applicationId: btg-B709IU6o9QNXUS4TVw
                  serviceId: null
                  endpointId: null
                  boundaryScope: INBOUND
                lastUpdated: 1732017541059
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SliConfigurationWithLastUpdated'
          description: OK
      security:
      - ApiKeyAuth:
        - Default
      summary: Get All SLI Configs
      tags:
      - SLI Settings
      x-ibm-ahub-byok: true
    post:
      deprecated: true
      operationId: createSliConfig
      requestBody:
        content:
          application/json:
            example:
              sliName: test-application-sli
              metricConfiguration:
                metricName: latency
                metricAggregation: P90
                threshold: 555
              sliEntity:
                sliType: application
                applicationId: btg-B709IU6o9QNXUS4TVw
                serviceId: null
                endpointId: null
                boundaryScope: INBOUND
            schema:
              $ref: '#/components/schemas/SliConfiguration'
        required: true
      responses:
        '200':
          content:
            application/json:
              example:
                id: 3J0RDgfyQz-P_hVzbNNb4A
                sliName: test-application-sli
                initialEvaluationTimestamp: 1732017600000
                metricConfiguration:
                  metricName: latency
                  metricAggregation: P90
                  threshold: 555
                sliEntity:
                  sliType: application
                  applicationId: btg-B709IU6o9QNXUS4TVw
                  serviceId: null
                  endpointId: null
                  boundaryScope: INBOUND
                lastUpdated: 1732017541059
              schema:
                $ref: '#/components/schemas/SliConfigurationWithLastUpdated'
          description: OK
      security:
      - ApiKeyAuth:
        - canConfigureServiceLevels
      summary: Create SLI Config
      tags:
      - SLI Settings
      x-ibm-ahub-byok: true
      description: 'This endpoint creates the Service Level Indicator Configuration


        ## Mandatory Parameters:


        - **id** A unique identifier for each SLI configuration


        - **sliName:** Name for the SLI configuration


        - **sliEntity:** Entity of the SLI configuration


        ### SLI Entity specific parameters


        Depending on the chosen `sliType` in the `sliEntity`, there are further required parameters:


        #### Application SLI entity


        This option can be used to create a Time-Based SLI


        - **sliEntity.applicationId:** The Id of the Application Perspective


        - **sliEntity.boundaryScope:** Boundary scope of the Application Perspective


        - **metricConfiguration.metricName:** The metric name on which to compute the SLI


        - **metricConfiguration.metricAggregation:** The aggregation of the metric


        - **metricConfiguration.threshold:** Threshold for the metric


        #### Availability SLI entity


        This opetion can be used to create an Event-Based SLI


        - **sliEntity.applicationId:** The Id of the Application Perspective


        - **sliEntity.boundaryScope:** Boundary scope of the Application Perspective


        ## Deprecated Parameters for Availability SLI entity:


        - **sliEntity.serviceId:** The ID if the Service in he context of an Application Perspective


        - **sliEntity.endpointId:** The ID of an Endpoint belonging to a Service


        - **sliEntity.goodEventFilters:** The list of TagFilters to match good events / calls


        - **sliEntity.badEventFilters:** The list of TagFilters to match bad events / calls


        All of these filters can be included using the list of TagFilterExpressions via **sliEntity.goodEventFilterExpression** and **sliEntity.badEventFilterExpression**.

        These parameters will be removed in the upcoming releases.'
  /api/settings/sli/{id}:
    delete:
      deprecated: true
      operationId: deleteSliConfig
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
          description: Service Levels Indicator ID
          example: 7iydEfqJQP6AKzd3yR3byw
      responses:
        default:
          content:
            application/json: {}
          description: default response
      security:
      - ApiKeyAuth:
        - canConfigureServiceLevels
      summary: Delete SLI Config
      tags:
      - SLI Settings
      x-ibm-ahub-byok: true
    get:
      deprecated: true
      operationId: getSliConfig
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
          description: Service Levels Indicator ID
          example: 3J0RDgfyQz-P_hVzbNNb4A
      responses:
        '200':
          content:
            application/json:
              example:
                id: 3J0RDgfyQz-P_hVzbNNb4A
                sliName: test-application-sli
                initialEvaluationTimestamp: 1732017600000
                metricConfiguration:
                  metricName: latency
                  metricAggregation: P90
                  threshold: 555
                sliEntity:
                  sliType: application
                  applicationId: btg-B709IU6o9QNXUS4TVw
                  serviceId: null
                  endpointId: null
                  boundaryScope: INBOUND
                lastUpdated: 1732017541059
              schema:
                $ref: '#/components/schemas/SliConfigurationWithLastUpdated'
          description: OK
      security:
      - ApiKeyAuth:
        - Default
      summary: Get SLI Config
      tags:
      - SLI Settings
      x-ibm-ahub-byok: true
    put:
      deprecated: true
      operationId: updateSliConfig
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
          description: Service Levels Indicator ID
          example: 3J0RDgfyQz-P_hVzbNNb4A
      requestBody:
        content:
          application/json:
            example:
              id: 3J0RDgfyQz-P_hVzbNNb4A
              sliName: test-application-sli
              initialEvaluationTimestamp: 1732017600000
              metricConfiguration:
                metricName: latency
                metricAggregation: P90
                threshold: 555
              sliEntity:
                sliType: application
                applicationId: btg-B709IU6o9QNXUS4TVw
                serviceId: null
                endpointId: null
                boundaryScope: INBOUND
              lastUpdated: 1732017541059
            schema:
              $ref: '#/components/schemas/SliConfiguration'
        required: true
      responses:
        '200':
          content:
            application/json:
              example:
                id: 3J0RDgfyQz-P_hVzbNNb4A
                sliName: test-application-sli
                initialEvaluationTimestamp: 1732017600000
                metricConfiguration:
                  metricName: latency
                  metricAggregation: P90
                  threshold: 555
                sliEntity:
                  sliType: application
                  applicationId: btg-B709IU6o9QNXUS4TVw
                  serviceId: null
                  endpointId: null
                  boundaryScope: INBOUND
                lastUpdated: 1732017541059
              schema:
                $ref: '#/components/schemas/SliConfigurationWithLastUpdated'
          description: OK
      security:
      - ApiKeyAuth:
        - canConfigureServiceLevels
      summary: Update SLI Config
      tags:
      - SLI Settings
      x-ibm-ahub-byok: true
  /api/settings/v2/sli:
    get:
      operationId: getAllSliConfigsV2
      responses:
        '200':
          content:
            application/json:
              example:
              - id: T0yCMBR4G
                sliName: Siva SLI test
                initialEvaluationTimestamp: 1637758860000
                metricConfiguration:
                  metricName: latency
                  metricAggregation: P90
                  threshold: 100
                sliEntity:
                  sliType: application
                  applicationId: 1qvXgVfLTNqi8gGTcCaNUw
                  serviceId: 6097d596c3d9024034b3d03b2b5c43acea65e5a4
                  endpointId: oETFj2WyPusvXgRW_181J3fH_t8
                  boundaryScope: INBOUND
                lastUpdated: 1637758839104
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SliConfigurationWithLastUpdated'
          description: OK
      security:
      - ApiKeyAuth:
        - Default
      summary: Get All SLI Configs
      tags:
      - SLI Settings
      x-ibm-ahub-byok: true
    post:
      operationId: createSliConfigV2
      requestBody:
        content:
          application/json:
            example:
              sliName: test-application-sli
              metricConfiguration:
                metricName: latency
                metricAggregation: P90
                threshold: 555
              sliEntity:
                sliType: application
                applicationId: btg-B709IU6o9QNXUS4TVw
                serviceId: null
                endpointId: null
                boundaryScope: INBOUND
            schema:
              $ref: '#/components/schemas/SliConfiguration'
        required: true
      responses:
        '200':
          content:
            application/json:
              example:
                id: 3J0RDgfyQz-P_hVzbNNb4A
                sliName: test-application-sli
                initialEvaluationTimestamp: 1732017600000
                metricConfiguration:
                  metricName: latency
                  metricAggregation: P90
                  threshold: 555
                sliEntity:
                  sliType: application
                  applicationId: btg-B709IU6o9QNXUS4TVw
                  serviceId: null
                  endpointId: null
                  boundaryScope: INBOUND
                lastUpdated: 1732017541059
              schema:
                $ref: '#/components/schemas/SliConfigurationWithLastUpdated'
          description: New SLI Configuration Created Successfully
        '400':
          content:
            application/json:
              example: '{"errors":["Unknown tag filter: call.eron"]}'
              schema:
                type: string
          description: Bad Request
        '422':
          content:
            application/json:
              example: '{"errors":["sliEntity.entityId must not be blank"]}'
              schema:
                type: string
          description: Unprocessable Entity
      security:
      - ApiKeyAuth:
        - canConfigureServiceLevels
      summary: Create SLI Config
      tags:
      - SLI Settings
      x-ibm-ahub-byok: true
      description: 'This endpoint creates the Service Level Indicator Configuration


        ## Mandatory Parameters:


        - **id** A unique identifier for each SLI configuration


        - **sliName:** Name for the SLI configuration


        - **sliEntity:** Entity of the SLI configuration


        ### SLI Entity specific parameters


        Depending on the chosen `sliType` in the `sliEntity`, there are further required parameters:


        #### Application SLI entity


        This option can be used to create a Time-Based SLI


        - **sliEntity.applicationId:** The Id of the Application Perspective


        - **sliEntity.boundaryScope:** Boundary scope of the Application Perspective


        - **metricConfiguration.metricName:** The metric name on which to compute the SLI


        - **metricConfiguration.metricAggregation:** The aggregation of the metric


        - **metricConfiguration.threshold:** Threshold for the metric


        #### Availability SLI entity


        This opetion can be used to create an Event-Based SLI


        - **sliEntity.applicationId:** The Id of the Application Perspective


        - **sliEntity.boundaryScope:** Boundary scope of the Application Perspective


        ## Deprecated Parameters for Availability SLI entity:


        - **sliEntity.serviceId:** The ID if the Service in he context of an Application Perspective


        - **sliEntity.endpointId:** The ID of an Endpoint belonging to a Service


        - **sliEntity.goodEventFilters:** The list of TagFilters to match good events / calls


        - **sliEntity.badEventFilters:** The list of TagFilters to match bad events / calls


        All of these filters can be included using the list of TagFilterExpressions via **sliEntity.goodEventFilterExpression** and **sliEntity.badEventFilterExpression**.

        These parameters will be removed in the upcoming releases.'
  /api/settings/v2/sli/{entityType}/{entityId}:
    get:
      operationId: getSliConfigsForEntityTypeAndIdV2
      parameters:
      - description: Type of the Entity, whether it is an application or website
        in: path
        name: entityType
        required: true
        schema:
          type: string
          enum:
          - APPLICATION
          - WEBSITE
      - description: Unique ID of the Entity
        example: DkPX-x9VQuKBKopuilrkYw
        in: path
        name: entityId
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              example:
              - id: HXcNRWhDSWiZs3HiUAKr7g
                sliName: turbo time 1
                initialEvaluationTimestamp: 1648133520000
                metricConfiguration:
                  metricName: latency
                  metricAggregation: P90
                  threshold: 300
                sliEntity:
                  sliType: application
                  applicationId: 1qvXgVfLTNqi8gGTcCaNUw
                  serviceId: null
                  endpointId: null
                  boundaryScope: INBOUND
                lastUpdated: 1648133508938
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SliConfigurationWithLastUpdated'
          description: OK
      security:
      - ApiKeyAuth:
        - Default
      summary: Get all SLI configs for entity type and entity id
      tags:
      - SLI Settings
      x-ibm-ahub-byok: true
  /api/settings/v2/sli/{id}:
    delete:
      operationId: deleteSliConfigV2
      parameters:
      - description: ID of the Service Level Indicator (SLI)
        example: HXcNRWhDSWiZs3HiUAKr7g
        in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '204':
          description: SLI Configuration Deleted Successfully
      security:
      - ApiKeyAuth:
        - canConfigureServiceLevels
      summary: Delete SLI Config
      tags:
      - SLI Settings
      x-ibm-ahub-byok: true
    get:
      operationId: getSliConfigV2
      parameters:
      - description: ID of the Service Level Indicator (SLI)
        example: HXcNRWhDSWiZs3HiUAKr7g
        in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              example:
              - id: HXcNRWhDSWiZs3HiUAKr7g
                sliName: turbo time 1
                initialEvaluationTimestamp: 1648133520000
                metricConfiguration:
                  metricName: latency
                  metricAggregation: P90
                  threshold: 300
                sliEntity:
                  sliType: application
                  applicationId: 1qvXgVfLTNqi8gGTcCaNUw
                  serviceId: null
                  endpointId: null
                  boundaryScope: INBOUND
                lastUpdated: 1648133508938
              schema:
                $ref: '#/components/schemas/SliConfigurationWithLastUpdated'
          description: OK
        '404':
          content:
            application/json:
              example:
                errors:
                - The SLI Configuration you are looking for does not exist.
              schema:
                type: string
          description: SLI Configuration Not Found
      security:
      - ApiKeyAuth:
        - Default
      summary: Get SLI Config
      tags:
      - SLI Settings
      x-ibm-ahub-byok: true
components:
  schemas:
    MetricConfiguration:
      type: object
      description: Details regarding the metric to be configured, including the metric name, threshold, and aggregation method
      properties:
        metricAggregation:
          type: string
          description: 'Specifies the types of aggregations that can be applied to a series of values.

            For example, `P25` refers to the 25th percentile. Note that not all aggregation methods are available for every metric.

            For instance, the `Call count` metric supports only the `SUM` aggregation, whereas the `Error rate` metric only supports the `MEAN` aggregation.

            '
          enum:
          - SUM
          - MEAN
          - MAX
          - MIN
          - P25
          - P50
          - P75
          - P90
          - P95
          - P98
          - P99
          - P99_9
          - P99_99
          - DISTINCT_COUNT
          - SUM_POSITIVE
          - PER_SECOND
          - INCREASE
        metricName:
          type: string
          description: Defines the name of the metric to be monitored. Examples include `calls` and `latency`
        threshold:
          type: number
          format: double
          description: Specifies the threshold value for the metric being monitored
          exclusiveMinimum: 0
      required:
      - metricName
    SliEntity:
      type: object
      description: Entity Type of the SLI Configuration
      discriminator:
        mapping:
          application: '#/components/schemas/ApplicationSliEntity'
          availability: '#/components/schemas/AvailabilitySliEntity'
          websiteEventBased: '#/components/schemas/WebsiteEventBasedSliEntity'
          websiteTimeBased: '#/components/schemas/WebsiteTimeBasedSliEntity'
        propertyName: sliType
      properties:
        sliType:
          type: string
      required:
      - sliType
    SliConfigurationWithLastUpdated:
      type: object
      properties:
        id:
          type: string
          description: Unique ID for each SLI
          maxLength: 64
          minLength: 0
        initialEvaluationTimestamp:
          type: integer
          format: int64
          description: Initial evaluation timestamp in milliseconds (13-digit)
        lastUpdated:
          type: integer
          format: int64
          description: Last Updated timestamp in milliseconds (13-digit)
          minimum: 1
        metricConfiguration:
          $ref: '#/components/schemas/MetricConfiguration'
        sliEntity:
          $ref: '#/components/schemas/SliEntity'
        sliName:
          type: string
          description: The name of the Service Level Indicator (SLI) specified during its creation
          maxLength: 256
          minLength: 0
      required:
      - id
      - sliEntity
      - sliName
    SliConfiguration:
      type: object
      properties:
        id:
          type: string
          description: Unique ID for each SLI
          maxLength: 64
          minLength: 0
        initialEvaluationTimestamp:
          type: integer
          format: int64
          description: Initial evaluation timestamp in milliseconds (13-digit)
        metricConfiguration:
          $ref: '#/components/schemas/MetricConfiguration'
        sliEntity:
          $ref: '#/components/schemas/SliEntity'
        sliName:
          type: string
          description: The name of the Service Level Indicator (SLI) specified during its creation
          maxLength: 256
          minLength: 0
      required:
      - id
      - sliEntity
      - sliName
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: authorization
      type: apiKey
      description: "## Example\n\n```bash\ncurl --request GET \\\n  --url https://test-instana.instana.io/api/application-monitoring/catalog/metrics \\\n  --header 'authorization: apiToken xxxxxxxxxxxxxxxx'\n```\n"
x-tagGroups:
- name: Websites & Mobile Apps
  tags:
  - Website Metrics
  - Website Catalog
  - Website Analyze
  - Website Configuration
  - Mobile App Metrics
  - Mobile App Catalog
  - Mobile App Analyze
  - Mobile App Configuration
  - End User Monitoring
- name: Applications
  tags:
  - Application Metrics
  - Application Resources
  - Application Catalog
  - Application Analyze
  - Application Settings
  - Application Topology
  - Application Alert Configuration
  - Global Application Alert Configuration
- name: Infrastructure
  tags:
  - Infrastructure Analyze
  - Infrastructure Metrics
  - Infrastructure Resources
  - Infrastructure Catalog
  - Infrastructure Topology
- name: Logging
  tags:
  - Logging Analyze
- name: Synthetic Monitoring
  tags:
  - Synthetic Catalog
  - Synthetic Metrics
  - Synthetic Settings
  - Synthetic Test Playback Results
  - Synthetic Alert Configuration
- name: Logs
  tags:
  - Log Alert Configuration
- name: Events
  tags:
  - Events
  - Event Settings
- name: Automation
  tags:
  - Action Catalog
  - Action History
  - Policies
- name: Service Levels
  tags:
  - SLI Settings
  - SLI Report
  - Apdex Settings
  - Apdex Report
  - Service Levels Objective(SLO) Configurations
  - Service Levels Objective(SLO) Report
  - Service Levels Alert Configuration
  - SLO Correction Configurations
  - SLO Correction Windows
- name: AI Management
  tags:
  - AI Management
- name: Settings
  tags:
  - Custom Dashboards
  - User
  - Groups
  - Teams
  - Roles
  - Audit Log
  - API Token
  - Maintenance Configuration
  - Synthetic Calls
  - Session Settings
  - Automation Settings
  - Authentication
- name: Open Beta Features
  tags:
  - Infrastructure Analyze
- name: Closed Beta Features
  tags:
  - Infrastructure Alert Configuration
- name: Instana
  tags:
  - Releases
  - Host Agent
  - Health
  - Usage
