openapi: 3.2.0
info:
  contact:
    email: support@instana.com
    name: © Instana
    url: http://instana.com
  termsOfService: https://www.instana.com/terms-of-use/
  title: Instana REST API documentation User API
  version: 1.307.1417
  x-ibm-ahub-try: true
  x-logo:
    altText: instana logo
    backgroundColor: '#FAFBFC'
    url: header-logo.svg
  description: Searching for answers and best pratices?
servers:
- description: Instana Backend
  url: https://{unit}-{tenant}.instana.io
  variables:
    tenant:
      default: tenant
      description: Customer tenant unit
    unit:
      default: unit
      description: Customer tenant name
- description: Instana Self-Hosted Backend
  url: https://{domain}
  variables:
    domain:
      default: example.com
      description: Customer Self-Hosted domain
tags:
- name: User
paths:
  /api/settings/invitation/share:
    post:
      operationId: shareAndInviteUsers
      requestBody:
        content:
          application/json:
            example:
            - email: username@example.com
              groupId: '-1'
              message: hello message
              path: /testpath
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Invitation'
        required: true
      responses:
        '200':
          content:
            application/json:
              example:
                invitationResults:
                - userEmail: username@example.com
                  invitationStatus: SUCCESS
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/InvitationResponse'
          description: OK
        '400':
          content:
            application/json:
              example:
                errors:
                - Please set at least one email
              schema:
                type: string
          description: Bad Request Error
      security:
      - ApiKeyAuth:
        - CanConfigureUsers
      summary: Send user invitations
      tags:
      - User
      x-ibm-ahub-byok: true
      description: 'This API endpoint allows to invite users to this tenant.

        Each user requires the email address and the group to which the user will be added initially.


        Inviting users whilst an IdP is configured will always result in failures, as in this case users will be provisioned during the login based on the IdP configuration.

        During the IdP configurations all pending invitations are automatically revoked.


        Inviting users who are already members of the tenant will also provide an error result.'
  /api/settings/invitations:
    delete:
      operationId: revokePendingInvitation
      parameters:
      - description: Email of the invite for removal
        example: username@example.com
        in: query
        name: email
        required: true
        schema:
          type: string
      responses:
        default:
          content:
            application/json: {}
          description: default response
      security:
      - ApiKeyAuth:
        - CanConfigureUsers
      summary: Revoke pending invitation
      tags:
      - User
      x-ibm-ahub-byok: true
      description: This API endpoint allows to delete an invitation, requires the users’ email as a Query parameter.
    get:
      operationId: getInvitations
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/InvitationResult'
          description: OK
      security:
      - ApiKeyAuth:
        - CanConfigureUsers
      summary: All pending invitations
      tags:
      - User
      x-ibm-ahub-byok: true
      description: 'This API endpoint retrieves the list of all pending invitations.

        During the IdP configuration all pending invitations will be dismissed and whilst an IdP is configured invitations are prevented.'
    post:
      operationId: inviteUsers
      requestBody:
        content:
          application/json:
            example:
            - email: username@example.com
              groupId: '-1'
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Invitation'
        required: true
      responses:
        '200':
          content:
            application/json:
              example:
                invitationResults:
                - userEmail: username@example.com
                  invitationStatus: SUCCESS
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/InvitationResponse'
          description: OK
        '400':
          content:
            application/json:
              example:
                errors:
                - Please set at least one email
              schema:
                type: string
          description: Bad Request Error
      security:
      - ApiKeyAuth:
        - CanConfigureUsers
      summary: Send user invitations
      tags:
      - User
      x-ibm-ahub-byok: true
      description: 'This API endpoint allows to invite users to this tenant.

        Each user requires the email address and the group to which the user will be added initially.


        Inviting users whilst an IdP is configured will always result in failures, as in this case users will be provisioned during the login based on the IdP configuration.

        During the IdP configurations all pending invitations are automatically revoked.


        Inviting users who are already members of the tenant will also provide an error result.'
  /api/settings/users:
    get:
      description: Retrieves all users with access to the tenant. The result will not contain pending invitations.
      operationId: getUsers
      responses:
        '200':
          content:
            application/json:
              example:
              - id: userId
                email: username@example.com
                fullName: username
                lastLoggedIn: 1636434847190
                groupCount: 1
                tfaEnabled: false
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserResult'
          description: OK
        '401':
          description: Unauthorized access - requires user authentication.
        '403':
          description: Insufficient permissions.
      security:
      - ApiKeyAuth:
        - CanConfigureUsers
      summary: All users (without invitations)
      tags:
      - User
      x-ibm-ahub-byok: true
  /api/settings/users/delete:
    put:
      description: Remove multiple users access to the tenant. Removing a user from a tenant does not delete their user account.
      operationId: removeUsersFromTenant
      requestBody:
        content:
          '*/*':
            schema:
              type: array
              items:
                type: string
              uniqueItems: true
        required: true
      responses:
        '204':
          description: Successful - no content to return.
        '401':
          description: Unauthorized access - requires user authentication.
        '403':
          description: Insufficient permissions.
      security:
      - ApiKeyAuth:
        - CanConfigureUsers
      summary: Remove users from tenant
      tags:
      - User
      x-ibm-ahub-byok: true
  /api/settings/users/overview:
    get:
      description: Retrieves all users with access to the tenant. The result will also contain pending invitations.
      operationId: getUsersIncludingInvitations
      responses:
        '200':
          content:
            application/json:
              example:
                users:
                - id: userId1
                  email: username@example.com
                  fullName: fullName
                  lastLoggedIn: 1699313025975
                  groupCount: null
                  tfaEnabled: null
                invitations:
                - id: userId2
                  email: username2@example.com
                  groupId: '-3'
              schema:
                $ref: '#/components/schemas/UsersResult'
          description: OK
        '401':
          description: Unauthorized access - requires user authentication.
        '403':
          description: Insufficient permissions.
      security:
      - ApiKeyAuth:
        - CanConfigureUsers
      summary: All users (incl. invitations)
      tags:
      - User
      x-ibm-ahub-byok: true
  /api/settings/users/{email}:
    put:
      description: Updates the full name of the user.
      operationId: updateUser
      parameters:
      - in: path
        name: email
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            example:
              fullName: Updated Name
            schema:
              $ref: '#/components/schemas/EditUser'
      responses:
        '204':
          description: Successful - no content to return.
        '401':
          description: Unauthorized access - requires user authentication.
        '403':
          description: Insufficient permissions.
        '404':
          description: Resource not found.
      security:
      - ApiKeyAuth:
        - CanConfigureUsers
      summary: Change user name of single user
      tags:
      - User
      x-ibm-ahub-byok: true
  /api/settings/users/{userId}:
    delete:
      description: Remove the users access to the tenant. Removing a user from a tenant does not delete their user account.
      operationId: removeUserFromTenant
      parameters:
      - description: Id of the user for removal
        example: userId
        in: path
        name: userId
        required: true
        schema:
          type: string
      responses:
        '204':
          description: Successful - no content to return.
        '401':
          description: Unauthorized access - requires user authentication.
        '403':
          description: Insufficient permissions.
      security:
      - ApiKeyAuth:
        - CanConfigureUsers
      summary: Remove user from tenant
      tags:
      - User
      x-ibm-ahub-byok: true
    get:
      description: Retrieves the user with access to the tenant.
      operationId: getUserById
      parameters:
      - description: Id of the user for retrieval
        example: userId
        in: path
        name: userId
        required: true
        schema:
          type: string
        style: simple
      responses:
        '200':
          content:
            application/json:
              example:
                id: userId
                preferredName: preferredName
                fullName: fullName
                email: username@example.com
                encryptedPassword: ''
                lastLoggedIn: 1699442707385
                timestampAcceptedTos: 1696404223545
                timestampAcceptedPrivacyAgreement: 1696404223545
                acceptedTosVersion: 6
                acceptedPrivacyAgreementVersion: 9
                tenantsWhereMainContact: []
                tenants: []
                createDate: 1696404196256
                emailConfirmed: true
                tenantIds:
                - 55557f97186b9c0007857730
                passwordResetAttempt: 0
                groupCount: null
                tfaEnabled: null
                role: null
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserResult'
          description: OK
        '401':
          description: Unauthorized access - requires user authentication.
        '403':
          description: Insufficient permissions.
      security:
      - ApiKeyAuth:
        - CanConfigureUsers
      summary: Get single user
      tags:
      - User
      x-ibm-ahub-byok: true
components:
  schemas:
    UsersResult:
      type: object
      properties:
        invitations:
          type: array
          items:
            $ref: '#/components/schemas/InvitationResult'
          uniqueItems: true
        users:
          type: array
          items:
            $ref: '#/components/schemas/UserResult'
          uniqueItems: true
    InvitationResult:
      type: object
      properties:
        invitationStatus:
          type: string
          enum:
          - SUCCESS
          - INTERNAL_ERROR
          - FAILURE_USER_ALREADY_EXISTS
          - FAILURE_USER_ALREADY_INVITED
          - FAILURE_ONLY_DEFAULT_GROUP_INVITATION_ALLOWED
          - FAILURE_TENANT_IDP_CONFIGURED
        userEmail:
          type: string
    Invitation:
      type: object
      properties:
        email:
          type: string
        groupId:
          type: string
        message:
          type: string
        path:
          type: string
      required:
      - email
      - groupId
    EditUser:
      type: object
      properties:
        fullName:
          type: string
      required:
      - fullName
    UserResult:
      type: object
      properties:
        email:
          type: string
        fullName:
          type: string
        groupCount:
          type: integer
          format: int64
        id:
          type: string
        lastLoggedIn:
          type: integer
          format: int64
        tfaEnabled:
          type: boolean
      required:
      - email
      - fullName
      - id
    InvitationResponse:
      type: object
      properties:
        invitationResults:
          type: array
          items:
            $ref: '#/components/schemas/InvitationResult'
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: authorization
      type: apiKey
      description: "## Example\n\n```bash\ncurl --request GET \\\n  --url https://test-instana.instana.io/api/application-monitoring/catalog/metrics \\\n  --header 'authorization: apiToken xxxxxxxxxxxxxxxx'\n```\n"
x-tagGroups:
- name: Websites & Mobile Apps
  tags:
  - Website Metrics
  - Website Catalog
  - Website Analyze
  - Website Configuration
  - Mobile App Metrics
  - Mobile App Catalog
  - Mobile App Analyze
  - Mobile App Configuration
  - End User Monitoring
- name: Applications
  tags:
  - Application Metrics
  - Application Resources
  - Application Catalog
  - Application Analyze
  - Application Settings
  - Application Topology
  - Application Alert Configuration
  - Global Application Alert Configuration
- name: Infrastructure
  tags:
  - Infrastructure Analyze
  - Infrastructure Metrics
  - Infrastructure Resources
  - Infrastructure Catalog
  - Infrastructure Topology
- name: Logging
  tags:
  - Logging Analyze
- name: Synthetic Monitoring
  tags:
  - Synthetic Catalog
  - Synthetic Metrics
  - Synthetic Settings
  - Synthetic Test Playback Results
  - Synthetic Alert Configuration
- name: Logs
  tags:
  - Log Alert Configuration
- name: Events
  tags:
  - Events
  - Event Settings
- name: Automation
  tags:
  - Action Catalog
  - Action History
  - Policies
- name: Service Levels
  tags:
  - SLI Settings
  - SLI Report
  - Apdex Settings
  - Apdex Report
  - Service Levels Objective(SLO) Configurations
  - Service Levels Objective(SLO) Report
  - Service Levels Alert Configuration
  - SLO Correction Configurations
  - SLO Correction Windows
- name: AI Management
  tags:
  - AI Management
- name: Settings
  tags:
  - Custom Dashboards
  - User
  - Groups
  - Teams
  - Roles
  - Audit Log
  - API Token
  - Maintenance Configuration
  - Synthetic Calls
  - Session Settings
  - Automation Settings
  - Authentication
- name: Open Beta Features
  tags:
  - Infrastructure Analyze
- name: Closed Beta Features
  tags:
  - Infrastructure Alert Configuration
- name: Instana
  tags:
  - Releases
  - Host Agent
  - Health
  - Usage
