openapi: 3.2.0
info:
  contact:
    email: support@instana.com
    name: © Instana
    url: http://instana.com
  termsOfService: https://www.instana.com/terms-of-use/
  title: Instana REST API documentation Service Levels Alert…
  version: 1.307.1417
  x-ibm-ahub-try: true
  x-logo:
    altText: instana logo
    backgroundColor: '#FAFBFC'
    url: header-logo.svg
  description: Searching for answers and best pratices?
servers:
- description: Instana Backend
  url: https://{unit}-{tenant}.instana.io
  variables:
    tenant:
      default: tenant
      description: Customer tenant unit
    unit:
      default: unit
      description: Customer tenant name
- description: Instana Self-Hosted Backend
  url: https://{domain}
  variables:
    domain:
      default: example.com
      description: Customer Self-Hosted domain
tags:
- name: Service Levels Alert Configuration
paths:
  /api/events/settings/global-alert-configs/service-levels:
    get:
      description: Configs are sorted descending by their created date.
      operationId: findActiveServiceLevelsAlertConfigs
      parameters:
      - description: Service Levels Objective(SLO) Configuration ID
        example: SLOEANnWh9tQOa2h88kGxK6wQ
        in: query
        name: sloId
        schema:
          type: string
      - description: List of Service Levels Alert Configuration IDs
        example: ln3IGogYS-S7CPqcOQYTNA
        in: query
        name: alertIds
        schema:
          type: array
          items:
            type: string
          maxItems: 1000
          minItems: 0
          uniqueItems: true
      responses:
        '200':
          content:
            application/json:
              example:
                name: Error Budget Remaining is low
                description: Error Budget Remaining is less than or equal to 5%.
                severity: 5
                triggering: true
                rule:
                  alertType: ERROR_BUDGET
                  metric: BURNED_PERCENTAGE
                threshold:
                  type: staticThreshold
                  operator: '>='
                  value: 0.05
                  lastUpdated: 1716454787342
                sloIds:
                - SLOEANnWh9tQOa2h88kGxK6wQ
                alertChannelIds: []
                timeThreshold:
                  expiry: null
                  timeWindow: 600000
                customPayloadFields:
                - type: staticString
                  key: foo
                  value: bar
                id: ln3IGogYS-S7CPqcOQYTNA
                created: 1717668384754
                initialCreated: 1717668384754
                readOnly: false
                enabled: true
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ServiceLevelseAlertConfigWithMetadata'
          description: Fetched list of the Service Level Alert Configurations Successfully
      security:
      - ApiKeyAuth:
        - Default
      summary: All Service levels Alert Configs
      tags:
      - Service Levels Alert Configuration
      x-ibm-ahub-byok: true
    post:
      operationId: createServiceLevelsAlertConfig
      requestBody:
        content:
          application/json:
            example:
              alertChannelIds: []
              customPayloadFields:
              - key: foo
                id: avvh9tbxpfRE65t
                type: staticString
                value: bar
              description: Error Budget Remaining is less than or equal to 5%.
              name: Error Budget Remaining is low
              rule:
                alertType: ERROR_BUDGET
                metric: BURNED_PERCENTAGE
              severity: 5
              sloIds:
              - SLOEANnWh9tQOa2h88kGxK6wQ
              threshold:
                type: staticThreshold
                value: 0.05
                operator: '>='
                lastUpdated: 1716454787342
              timeThreshold:
                timeWindow: 600000
              triggering: true
            schema:
              $ref: '#/components/schemas/ServiceLevelsAlertConfig'
        description: Create Request Body
        required: true
      responses:
        '200':
          content:
            application/json:
              example:
                name: Error Budget Remaining is low
                description: Error Budget Remaining is less than or equal to 5%.
                severity: 5
                triggering: true
                rule:
                  alertType: ERROR_BUDGET
                  metric: BURNED_PERCENTAGE
                threshold:
                  type: staticThreshold
                  operator: '>='
                  value: 0.05
                  lastUpdated: 1716454787342
                sloIds:
                - SLOEANnWh9tQOa2h88kGxK6wQ
                alertChannelIds: []
                timeThreshold:
                  expiry: null
                  timeWindow: 600000
                customPayloadFields:
                - type: staticString
                  key: foo
                  value: bar
                id: ln3IGogYS-S7CPqcOQYTNA
                created: 1717668384754
                initialCreated: 1717668384754
                readOnly: false
                enabled: true
              schema:
                $ref: '#/components/schemas/ServiceLevelseAlertConfigWithMetadata'
          description: Created new Service Levels Alert Configuration Successfully
        '400':
          content:
            application/json:
              example:
                errors:
                - Website SLOs do not support triggering -> true
              schema:
                type: array
                items:
                  type: string
          description: Service levels Alert Config with Website SLOs do not support triggering
      security:
      - ApiKeyAuth:
        - canConfigureServiceLevelSmartAlerts
      summary: Create Service levels Alert Config
      tags:
      - Service Levels Alert Configuration
      x-ibm-ahub-byok: true
  /api/events/settings/global-alert-configs/service-levels/{id}:
    delete:
      operationId: deleteServiceLevelsAlertConfig
      parameters:
      - description: Service Levels Alert Configuration ID
        example: ln3IGogYS-S7CPqcOQYTNA
        in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '204':
          description: Service Levels Alert Configuration Deleted Successfully
        '404':
          content:
            application/json:
              example: '{"errors":["Config with id: -DZZjflTQTmZ7yGvBilPlQ is not found"]}'
              schema:
                type: string
          description: Service levels Alert Config with given ID not found
      security:
      - ApiKeyAuth:
        - canConfigureServiceLevelSmartAlerts
      summary: Delete Service levels Alert Config
      tags:
      - Service Levels Alert Configuration
      x-ibm-ahub-byok: true
    get:
      description: Find a Service levels Alert Config by ID. This will deliver deleted configs too.
      operationId: findServiceLevelsAlertConfig
      parameters:
      - description: Service Levels Alert Configuration ID
        example: ln3IGogYS-S7CPqcOQYTNA
        in: path
        name: id
        required: true
        schema:
          type: string
      - description: Service Levels Alert Version Creation Date
        example: 1706617456952
        in: query
        name: validOn
        schema:
          type: integer
          format: int64
      responses:
        '200':
          content:
            application/json:
              example:
                name: Error Budget Remaining is low
                description: Error Budget Remaining is less than or equal to 5%.
                severity: 5
                triggering: true
                rule:
                  alertType: ERROR_BUDGET
                  metric: BURNED_PERCENTAGE
                threshold:
                  type: staticThreshold
                  operator: '>='
                  value: 0.05
                  lastUpdated: 1716454787342
                sloIds:
                - SLOEANnWh9tQOa2h88kGxK6wQ
                alertChannelIds: []
                timeThreshold:
                  expiry: null
                  timeWindow: 600000
                customPayloadFields:
                - type: staticString
                  key: foo
                  value: bar
                id: ln3IGogYS-S7CPqcOQYTNA
                created: 1717668384754
                initialCreated: 1717668384754
                readOnly: false
                enabled: true
              schema:
                $ref: '#/components/schemas/ServiceLevelseAlertConfigWithMetadata'
          description: Fetched Service Level Alert Configuration Successfully
        '404':
          content:
            application/json:
              example: '{"errors":["Config with id: -DZZjflTQTmZ7yGvBilPlQ is not found"]}'
              schema:
                type: string
          description: Service levels Alert Config with given ID not found
      security:
      - ApiKeyAuth:
        - Default
      summary: Get Service levels Alert Config
      tags:
      - Service Levels Alert Configuration
      x-ibm-ahub-byok: true
    post:
      operationId: updateServiceLevelsAlertConfig
      parameters:
      - description: Service Levels Alert Configuration ID
        example: ln3IGogYS-S7CPqcOQYTNA
        in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            example:
              alertChannelIds: []
              customPayloadFields:
              - key: foo
                id: avvh9tbxpfRE65t
                type: staticString
                value: bar
              description: Error Budget Remaining is less than or equal to 5%.
              name: Error Budget Remaining is low
              rule:
                alertType: ERROR_BUDGET
                metric: BURNED_PERCENTAGE
              severity: 5
              sloIds:
              - SLOEANnWh9tQOa2h88kGxK6wQ
              threshold:
                type: staticThreshold
                value: 0.05
                operator: '>='
                lastUpdated: 1716454787342
              timeThreshold:
                timeWindow: 600000
              triggering: true
            schema:
              $ref: '#/components/schemas/ServiceLevelsAlertConfig'
        description: Update Request Body
        required: true
      responses:
        '200':
          content:
            application/json:
              example:
                name: Error Budget Remaining is low
                description: Error Budget Remaining is less than or equal to 5%.
                severity: 5
                triggering: true
                rule:
                  alertType: ERROR_BUDGET
                  metric: BURNED_PERCENTAGE
                threshold:
                  type: staticThreshold
                  operator: '>='
                  value: 0.05
                  lastUpdated: 1716454787342
                sloIds:
                - SLOEANnWh9tQOa2h88kGxK6wQ
                alertChannelIds: []
                timeThreshold:
                  expiry: null
                  timeWindow: 600000
                customPayloadFields:
                - type: staticString
                  key: foo
                  value: bar
                id: ln3IGogYS-S7CPqcOQYTNA
                created: 1717668384754
                initialCreated: 1717668384754
                readOnly: false
                enabled: true
              schema:
                $ref: '#/components/schemas/ServiceLevelseAlertConfigWithMetadata'
          description: Updated Service Levels Alert Configuration Successfully
        '204':
          description: Service Levels Smart Alert Configuration did not change
        '400':
          content:
            application/json:
              example:
                errors:
                - Website SLOs do not support triggering -> true
              schema:
                type: array
                items:
                  type: string
          description: Service levels Alert Config with Website SLOs do not support triggering
      security:
      - ApiKeyAuth:
        - canConfigureServiceLevelSmartAlerts
      summary: Update Service levels Alert Config
      tags:
      - Service Levels Alert Configuration
      x-ibm-ahub-byok: true
  /api/events/settings/global-alert-configs/service-levels/{id}/disable:
    put:
      operationId: disableServiceLevelsAlertConfig
      parameters:
      - description: Service Levels Alert Configuration ID
        example: ln3IGogYS-S7CPqcOQYTNA
        in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type:
              - string
              - 'null'
      responses:
        '204':
          description: Service Levels Alert Configuration Disabled Successfully
        '404':
          content:
            application/json:
              example: '{"errors":["Config with id: -DZZjflTQTmZ7yGvBilPlQ is not found"]}'
              schema:
                type: string
          description: Service levels Alert Config with given ID not found
      security:
      - ApiKeyAuth:
        - canConfigureServiceLevelSmartAlerts
      summary: Disable Service levels Alert Config
      tags:
      - Service Levels Alert Configuration
      x-ibm-ahub-byok: true
  /api/events/settings/global-alert-configs/service-levels/{id}/enable:
    put:
      operationId: enableServiceLevelsAlertConfig
      parameters:
      - description: Service Levels Alert Configuration ID
        example: ln3IGogYS-S7CPqcOQYTNA
        in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type:
              - string
              - 'null'
      responses:
        '204':
          description: Service Levels Alert Configuration Enabled Successfully
        '404':
          content:
            application/json:
              example: '{"errors":["Config with id: -DZZjflTQTmZ7yGvBilPlQ is not found"]}'
              schema:
                type: string
          description: Service levels Alert Config with given ID not found
      security:
      - ApiKeyAuth:
        - canConfigureServiceLevelSmartAlerts
      summary: Enable Service levels Alert Config
      tags:
      - Service Levels Alert Configuration
      x-ibm-ahub-byok: true
  /api/events/settings/global-alert-configs/service-levels/{id}/restore/{created}:
    put:
      operationId: restoreServiceLevelsAlertConfig
      parameters:
      - description: Service Levels Alert Configuration ID
        example: ln3IGogYS-S7CPqcOQYTNA
        in: path
        name: id
        required: true
        schema:
          type: string
      - description: Service Levels Alert Version Creation Date
        example: 1706617456952
        in: path
        name: created
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              type:
              - string
              - 'null'
      responses:
        '204':
          description: Service Levels Alert Configuration Restored Successfully
        '404':
          content:
            application/json:
              example: '{"errors":["Config with id: -DZZjflTQTmZ7yGvBilPlQ is not found"]}'
              schema:
                type: string
          description: Service levels Alert Config with given ID not found
      security:
      - ApiKeyAuth:
        - canConfigureServiceLevelSmartAlerts
      summary: Restore Service levels Alert Config
      tags:
      - Service Levels Alert Configuration
      x-ibm-ahub-byok: true
  /api/events/settings/global-alert-configs/service-levels/{id}/versions:
    get:
      description: Find all versions of a Service levels Alert Config by ID. This will deliver deleted configs too. Configs are sorted descending by their created date.
      operationId: findServiceLevelsAlertConfigVersions
      parameters:
      - description: Service Levels Alert Configuration ID
        example: ln3IGogYS-S7CPqcOQYTNA
        in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              example:
              - id: ln3IGogYS-S7CPqcOQYTNA
                created: 1717507017767
                enabled: false
                deleted: false
                changeSummary:
                  changeType: DISABLE
                  author:
                    id: SCzqyU_LTtmO9CCnvvVOAg
                    type: API
                    fullName: userToken
              - id: ln3IGogYS-S7CPqcOQYTNA
                created: 1717506979607
                enabled: true
                deleted: false
                changeSummary:
                  changeType: CREATE
                  author:
                    id: SCzqyU_LTtmO9CCnvvVOAg
                    type: API
                    fullName: userToken
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ConfigVersion'
          description: Fetched list of Service Level Alert Configuration Versions Successfully
        '404':
          content:
            application/json:
              example: '{"errors":["Config with id: -DZZjflTQTmZ7yGvBilPlQ is not found"]}'
              schema:
                type: string
          description: Service levels Alert Config with given ID not found
      security:
      - ApiKeyAuth:
        - Default
      summary: Get versions of Service levels Alert Config
      tags:
      - Service Levels Alert Configuration
      x-ibm-ahub-byok: true
components:
  schemas:
    CustomPayloadField:
      type: object
      description: Custom payload fields to send additional information in the alert notifications. Can be left empty.
      discriminator:
        mapping:
          dynamic: '#/components/schemas/DynamicField'
          staticString: '#/components/schemas/StaticStringField'
        propertyName: type
      properties:
        key:
          type: string
          description: A user-specified unique identifier or name for a custom payload entry.
        type:
          type: string
      required:
      - key
      - type
    Author:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
          enum:
          - API
          - USER
          - INSTANA
          - UNKNOWN
    ChangeSummary:
      type: object
      description: Brief summary of changes made in this config version.
      properties:
        author:
          $ref: '#/components/schemas/Author'
        changeType:
          type: string
          enum:
          - CREATE
          - UPDATE
          - DELETE
          - ENABLE
          - DISABLE
          - RESTORE
          - UNKNOWN
      required:
      - author
      - changeType
    ServiceLevelsAlertRule:
      type: object
      description: This is the service levels alert type. It could be error budget alert or service levels object alert.
      discriminator:
        mapping:
          ERROR_BUDGET: '#/components/schemas/ErrorBudgetAlertRule'
          SERVICE_LEVELS_OBJECTIVE: '#/components/schemas/ServiceLevelObjectiveAlertRule'
        propertyName: alertType
      properties:
        alertType:
          type: string
      required:
      - alertType
    ServiceLevelsBurnRateTimeWindows:
      type: object
      deprecated: true
      description: This is the short and long time window setting for the burn rate alerts.
      properties:
        longTimeWindow:
          $ref: '#/components/schemas/AlertingTimeWindow'
        shortTimeWindow:
          $ref: '#/components/schemas/AlertingTimeWindow'
    StaticThreshold:
      type: object
      allOf:
      - $ref: '#/components/schemas/Threshold'
      - type: object
        properties:
          lastUpdated:
            type: integer
            format: int64
            minimum: 0
          value:
            type: number
            format: double
            minimum: 0
      description: This threshold defines a static value to be evaluated with a specific operator.
      required:
      - operator
    ServiceLevelsTimeThreshold:
      type: object
      description: This is the warm-up and cool-down setting to emit or stop alert event after threshold reached.
      properties:
        expiry:
          type: integer
          format: int64
          description: This is the cooldown period when the active alert misses threshold and stop emitting notification.
        timeWindow:
          type: integer
          format: int64
          description: This is the grace period when the threshold is reached and the alert becomes active to emit notification.
      required:
      - expiry
      - timeWindow
    ServiceLevelsBurnRateConfig:
      type: object
      description: This is the burn rate alert configuration which defines alerting windows and corresponding thresholds. This configuration must to specified for BURN_RATE_V2 Alerts.
      properties:
        alertWindowType:
          type: string
          description: 'Specifies the Burn Rate Alerting Window type: SINGLE for single window/threshold alerts, or LONG and SHORT for multi-window/threshold alerts.'
          enum:
          - SINGLE
          - LONG
          - SHORT
        duration:
          type: integer
          format: int32
          description: Duration of the Burn Rate Alerting Window.
        durationUnitType:
          type: string
          description: Duration Unit Type of the Burn Rate Alerting Window.
          enum:
          - millisecond
          - second
          - minute
          - hour
          - day
          - week
          - month
        threshold:
          $ref: '#/components/schemas/ServiceLevelsStaticThresholdConfig'
      required:
      - duration
      - durationUnitType
      - threshold
    ServiceLevelsStaticThresholdConfig:
      type: object
      description: This threshold defines a static value to be evaluated with a specific operator for burn rate v2 alerts.
      properties:
        lastUpdated:
          type: integer
          format: int64
          minimum: 0
        operator:
          type: string
          enum:
          - '>'
          - '>='
          - <
          - <=
        value:
          type: number
          format: double
          minimum: 0
      required:
      - operator
    ConfigVersion:
      type: object
      properties:
        changeSummary:
          $ref: '#/components/schemas/ChangeSummary'
        created:
          type: integer
          format: int64
          description: Unix timestamp representing the creation time of this revision.
          minimum: 1
        deleted:
          type: boolean
          deprecated: true
          description: Flag to indicate whether or not the configuration was deleted.
        enabled:
          type: boolean
          deprecated: true
          description: Flag to indicate whether or not the configuration is enabled.
        id:
          type: string
          description: ID of this configuration version.
          maxLength: 64
          minLength: 0
      required:
      - id
    ServiceLevelseAlertConfigWithMetadata:
      type: object
      properties:
        alertChannelIds:
          type: array
          description: This is the list of channel IDs when alert triggered and sent to.
          items:
            type: string
            description: This is the list of channel IDs when alert triggered and sent to.
          maxItems: 1024
          minItems: 0
          uniqueItems: true
        burnRateConfig:
          type: array
          description: This is the burn rate alert configuration which defines alerting windows and corresponding thresholds. This configuration must to specified for BURN_RATE_V2 Alerts.
          items:
            $ref: '#/components/schemas/ServiceLevelsBurnRateConfig'
          uniqueItems: true
        burnRateTimeWindows:
          $ref: '#/components/schemas/ServiceLevelsBurnRateTimeWindows'
        created:
          type: integer
          format: int64
          description: Created Date of the version of Service Levels Smart Alerts Configuration.
          minimum: 1
        customPayloadFields:
          type: array
          description: This is the custom name and value pairs to be sent along with the alert to the alert channels.
          items:
            $ref: '#/components/schemas/CustomPayloadField'
          maxItems: 20
          minItems: 0
        description:
          type: string
          description: The description of the alert. It is also the alert message content.
          maxLength: 65536
          minLength: 0
        enabled:
          type: boolean
          description: Boolean Parameter specifying the enabled state of Service Levels Smart Alerts Configuration.
        id:
          type: string
          description: Unique ID of the Service Levels Smart Alerts Configuration.
          maxLength: 64
          minLength: 0
        initialCreated:
          type: integer
          format: int64
          description: Created Date of the Initial version of Service Levels Smart Alerts Configuration.
          minimum: 1
        name:
          type: string
          description: Name of the Service Levels Smart Alerts Configuration.
          maxLength: 256
          minLength: 0
        readOnly:
          type: boolean
          description: Boolean Parameter specifying the readonly access to Service Levels Smart Alerts Configuration.
        rule:
          $ref: '#/components/schemas/ServiceLevelsAlertRule'
        severity:
          type: integer
          format: int32
          description: 'This is the severity of the alert. The value can be: <b>5</b>: warning, <b>10</b>: critical.'
        sloIds:
          type: array
          description: This is the list of SLO configurations related to this alert.
          items:
            type: string
            description: This is the list of SLO configurations related to this alert.
          maxItems: 1024
          minItems: 0
          uniqueItems: true
        threshold:
          $ref: '#/components/schemas/StaticThreshold'
        timeThreshold:
          $ref: '#/components/schemas/ServiceLevelsTimeThreshold'
        triggering:
          type: boolean
          description: Incident flag. If value is true, this alert will become an accident.
      required:
      - alertChannelIds
      - customPayloadFields
      - description
      - id
      - name
      - rule
      - severity
      - sloIds
      - timeThreshold
    Threshold:
      type: object
      deprecated: true
      description: Indicates the type of threshold this alert rule is evaluated on.
      discriminator:
        mapping:
          adaptiveBaseline: '#/components/schemas/AdaptiveBaseline'
          historicBaseline: '#/components/schemas/HistoricBaseline'
          staticThreshold: '#/components/schemas/StaticThreshold'
        propertyName: type
      properties:
        operator:
          type: string
          enum:
          - '>'
          - '>='
          - <
          - <=
        type:
          type: string
      required:
      - operator
      - type
    ServiceLevelsAlertConfig:
      type: object
      properties:
        alertChannelIds:
          type: array
          description: This is the list of channel IDs when alert triggered and sent to.
          items:
            type: string
            description: This is the list of channel IDs when alert triggered and sent to.
          maxItems: 1024
          minItems: 0
          uniqueItems: true
        burnRateConfig:
          type: array
          description: This is the burn rate alert configuration which defines alerting windows and corresponding thresholds. This configuration must to specified for BURN_RATE_V2 Alerts.
          items:
            $ref: '#/components/schemas/ServiceLevelsBurnRateConfig'
          uniqueItems: true
        burnRateTimeWindows:
          $ref: '#/components/schemas/ServiceLevelsBurnRateTimeWindows'
        customPayloadFields:
          type: array
          description: This is the custom name and value pairs to be sent along with the alert to the alert channels.
          items:
            $ref: '#/components/schemas/CustomPayloadField'
          maxItems: 20
          minItems: 0
        description:
          type: string
          description: The description of the alert. It is also the alert message content.
          maxLength: 65536
          minLength: 0
        name:
          type: string
          description: Name of the Service Levels Smart Alerts Configuration.
          maxLength: 256
          minLength: 0
        rule:
          $ref: '#/components/schemas/ServiceLevelsAlertRule'
        severity:
          type: integer
          format: int32
          description: 'This is the severity of the alert. The value can be: <b>5</b>: warning, <b>10</b>: critical.'
        sloIds:
          type: array
          description: This is the list of SLO configurations related to this alert.
          items:
            type: string
            description: This is the list of SLO configurations related to this alert.
          maxItems: 1024
          minItems: 0
          uniqueItems: true
        threshold:
          $ref: '#/components/schemas/StaticThreshold'
        timeThreshold:
          $ref: '#/components/schemas/ServiceLevelsTimeThreshold'
        triggering:
          type: boolean
          description: Incident flag. If value is true, this alert will become an accident.
      required:
      - alertChannelIds
      - customPayloadFields
      - description
      - name
      - rule
      - severity
      - sloIds
      - timeThreshold
    AlertingTimeWindow:
      type: object
      properties:
        duration:
          type: integer
          format: int32
        durationType:
          type: string
          enum:
          - millisecond
          - second
          - minute
          - hour
          - day
          - week
          - month
        durationUnit:
          type: string
          enum:
          - millisecond
          - second
          - minute
          - hour
          - day
          - week
          - month
          writeOnly: true
      required:
      - duration
      - durationType
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: authorization
      type: apiKey
      description: "## Example\n\n```bash\ncurl --request GET \\\n  --url https://test-instana.instana.io/api/application-monitoring/catalog/metrics \\\n  --header 'authorization: apiToken xxxxxxxxxxxxxxxx'\n```\n"
x-tagGroups:
- name: Websites & Mobile Apps
  tags:
  - Website Metrics
  - Website Catalog
  - Website Analyze
  - Website Configuration
  - Mobile App Metrics
  - Mobile App Catalog
  - Mobile App Analyze
  - Mobile App Configuration
  - End User Monitoring
- name: Applications
  tags:
  - Application Metrics
  - Application Resources
  - Application Catalog
  - Application Analyze
  - Application Settings
  - Application Topology
  - Application Alert Configuration
  - Global Application Alert Configuration
- name: Infrastructure
  tags:
  - Infrastructure Analyze
  - Infrastructure Metrics
  - Infrastructure Resources
  - Infrastructure Catalog
  - Infrastructure Topology
- name: Logging
  tags:
  - Logging Analyze
- name: Synthetic Monitoring
  tags:
  - Synthetic Catalog
  - Synthetic Metrics
  - Synthetic Settings
  - Synthetic Test Playback Results
  - Synthetic Alert Configuration
- name: Logs
  tags:
  - Log Alert Configuration
- name: Events
  tags:
  - Events
  - Event Settings
- name: Automation
  tags:
  - Action Catalog
  - Action History
  - Policies
- name: Service Levels
  tags:
  - SLI Settings
  - SLI Report
  - Apdex Settings
  - Apdex Report
  - Service Levels Objective(SLO) Configurations
  - Service Levels Objective(SLO) Report
  - Service Levels Alert Configuration
  - SLO Correction Configurations
  - SLO Correction Windows
- name: AI Management
  tags:
  - AI Management
- name: Settings
  tags:
  - Custom Dashboards
  - User
  - Groups
  - Teams
  - Roles
  - Audit Log
  - API Token
  - Maintenance Configuration
  - Synthetic Calls
  - Session Settings
  - Automation Settings
  - Authentication
- name: Open Beta Features
  tags:
  - Infrastructure Analyze
- name: Closed Beta Features
  tags:
  - Infrastructure Alert Configuration
- name: Instana
  tags:
  - Releases
  - Host Agent
  - Health
  - Usage
