openapi: 3.2.0
info:
  contact:
    email: support@instana.com
    name: © Instana
    url: http://instana.com
  termsOfService: https://www.instana.com/terms-of-use/
  title: Instana REST API documentation Groups API
  version: 1.307.1417
  x-ibm-ahub-try: true
  x-logo:
    altText: instana logo
    backgroundColor: '#FAFBFC'
    url: header-logo.svg
  description: Searching for answers and best pratices?
servers:
- description: Instana Backend
  url: https://{unit}-{tenant}.instana.io
  variables:
    tenant:
      default: tenant
      description: Customer tenant unit
    unit:
      default: unit
      description: Customer tenant name
- description: Instana Self-Hosted Backend
  url: https://{domain}
  variables:
    domain:
      default: example.com
      description: Customer Self-Hosted domain
tags:
- name: Groups
  description: Groups are used to permit individual users to perform specific actions and get visibility to an access scope.
paths:
  /api/settings/rbac/groups:
    get:
      operationId: getGroups
      responses:
        '200':
          content:
            application/json:
              example:
              - id: groupId1
                name: group1
                members:
                - userId: userId1
                  email: username1@example.com
                - userId: userId2
                  email: username2@example.com
              - id: groupId2
                name: group2
                members:
                - userId: userId1
                  email: username1@example.com
                - userId: userId3
                  email: username3@example.com
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApiGroup'
          description: OK
        '404':
          description: No groups found
      security:
      - ApiKeyAuth:
        - CanConfigureTeams
      summary: Get groups
      tags:
      - Groups
      x-ibm-ahub-byok: true
      description: 'Retrieve the list of all groups on the tenant together with the `Permission Set` for the tenant unit.


        The `Permission Set` object contains a set of permissions applied to the group.


        In case `permissions` include the entry e.g. `LIMITED_APPLICATIONS_SCOPE`, this group will have limited access to application area.


        The areas are included inside the `permissionSet`.


        The scopeRoleId is a fixed value for each area type:


        | Area | value |

        | ----------------------- | ------------- |

        | applicationIds | -100 |

        | kubernetesClusterUUIDs | -200 |

        | kubernetesNamespaceUIDs | -300 |

        | websiteIds | -400 |

        | mobileAppIds | -500 |

        | infraDfqFilter | -600 |


        For example:


        ```

        [

        {

        "id": "7hwdhtt7TU2CJDgYXgwwww",

        "name": "Scoped Group",

        "members": [

        {

        "userId": "61892cfdfcffab03016b2950",

        "email": "jhon@example.com"

        }

        ],

        "permissionSet": {

        "permissions": [

        "CAN_VIEW_LOGS",

        "CAN_VIEW_TRACE_DETAILS",

        "CAN_EDIT_ALL_ACCESSIBLE_CUSTOM_DASHBOARDS",

        "ACCESS_APPLICATIONS",

        "LIMITED_APPLICATIONS_SCOPE",

        "ACCESS_KUBERNETES",

        "LIMITED_KUBERNETES_SCOPE",

        "ACCESS_INFRASTRUCTURE_APPS",

        "LIMITED_INFRASTRUCTURE_SCOPE",

        "LIMITED_WEBSITES_SCOPE",


        ],

        "applicationIds": [

        {

        "scopeId": "1qvWgVfLTNqi9gGTcCaNUw",

        "scopeRoleId": "-100"

        }

        ],

        "kubernetesClusterUUIDs": [

        {

        "scopeId": "induced",

        "scopeRoleId": "-200"

        }

        ],

        "kubernetesNamespaceUIDs": [],

        "websiteIds": [],

        "mobileAppIds": [],

        "infraDfqFilter": {

        "scopeId": "production",

        "scopeRoleId": "-600"

        }

        }

        ]

        ```

        In this case `Scoped Group` has no access to websites due to having `LIMITED_WEBSITES_SCOPE` but not `ACCESS_WEBSITES`.


        Also due to having `LIMITED_APPLICATIONS_SCOPE`, the only visible application is the one with this id: `1qvWgVfLTNqi9gGTcCaNUw`.


        Same applies to `kubernetesClusterUUIDs`, `kubernetesNamespaceUIDs` and `infraDfqFilter`, with the only difference is that `infraDfqFilter`

        uses a filter "production" instead of an id.'
    post:
      operationId: createGroup
      requestBody:
        content:
          application/json:
            example:
              name: group name
              members:
              - userId: userId
                email: username@example.com
              permissionSet:
                permissions:
                - CAN_VIEW_LOGS
                applicationIds:
                - scopeId: scopeId1
                  scopeRoleId: '-102'
                kubernetesClusterUUIDs: []
                kubernetesNamespaceUIDs: []
                websiteIds: []
                mobileAppIds: []
                syntheticTestIds:
                - scopeId: scopeId10
                  scopeRoleId: '-1'
                restrictedApplicationFilter:
                  label: group name
                  tagFilterExpression:
                    type: TAG_FILTER
                    name: service.name
                    stringValue: acceptor
                    numberValue: null
                    booleanValue: null
                    key: null
                    value: acceptor
                    operator: EQUALS
                    entity: DESTINATION
                  scope: INCLUDE_NO_DOWNSTREAM
                infraDfqFilter:
                  scopeId: ''
                  scopeRoleId: '-1'
                actionFilter:
                  scopeId: ''
                  scopeRoleId: '-1'
            schema:
              $ref: '#/components/schemas/ApiCreateGroup'
        required: true
      responses:
        '200':
          content:
            application/json:
              example:
                name: group name
                members:
                - userId: userId
                  email: username@example.com
                permissionSet:
                  permissions:
                  - CAN_VIEW_LOGS
                  applicationIds:
                  - scopeId: scopeId1
                    scopeRoleId: '-102'
                  kubernetesClusterUUIDs: []
                  kubernetesNamespaceUIDs: []
                  websiteIds: []
                  mobileAppIds: []
                  syntheticTestIds:
                  - scopeId: scopeId10
                    scopeRoleId: '-1'
                  restrictedApplicationFilter:
                    label: group name
                    tagFilterExpression:
                      type: TAG_FILTER
                      name: service.name
                      stringValue: acceptor
                      numberValue: null
                      booleanValue: null
                      key: null
                      value: acceptor
                      operator: EQUALS
                      entity: DESTINATION
                    scope: INCLUDE_NO_DOWNSTREAM
                  infraDfqFilter:
                    scopeId: ''
                    scopeRoleId: '-1'
                  actionFilter:
                    scopeId: ''
                    scopeRoleId: '-1'
              schema:
                $ref: '#/components/schemas/ApiGroup'
          description: OK
      security:
      - ApiKeyAuth:
        - CanConfigureTeams
      summary: Create group
      tags:
      - Groups
      x-ibm-ahub-byok: true
      description: 'Creates a group on the tenant. Each group entry also needs a `Permission Set` per unit.


        The `Permission Set` object contains a set of permissions applied to the group.


        In case `permissions` include the entry e.g. `LIMITED_APPLICATIONS_SCOPE`, this group will have limited access to application area.


        Possible access permissions values are:


        - `ACCESS_APPLICATIONS`

        - `ACCESS_INFRASTRUCTURE`

        - `ACCESS_KUBERNETES`

        - `ACCESS_MOBILE_APPS`

        - `ACCESS_WEBSITES`

        - `LIMITED_APPLICATIONS_SCOPE`

        - `LIMITED_INFRASTRUCTURE_SCOPE`

        - `LIMITED_KUBERNETES_SCOPE`

        - `LIMITED_MOBILE_APPS_SCOPE`

        - `LIMITED_WEBSITES_SCOPE`


        The `id` value for the group is ignored, a new id is generated.


        The `scopeRoleId` is ignored, the id corresponding to the area is used.


        The `scopeId` is the id for the corresponding resource.'
  /api/settings/rbac/groups/delete:
    put:
      description: 'Delete multiple groups

        For more information on groups please access the https://developer.ibm.com/apis/catalog/instana--instana-rest-api/Settings#groups.'
      operationId: deleteGroups
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
              uniqueItems: true
        required: true
      responses:
        default:
          content:
            application/json: {}
          description: default response
      security:
      - ApiKeyAuth:
        - CanConfigureTeams
      summary: Delete groups
      tags:
      - Groups
      x-ibm-ahub-byok: true
  /api/settings/rbac/groups/user/{email}:
    get:
      operationId: getGroupsByUser
      parameters:
      - description: Email of the user for retrieval
        example: username@example.com
        in: path
        name: email
        required: true
        schema:
          type: string
        style: simple
      responses:
        '200':
          content:
            application/json:
              example:
              - id: groupId
                name: group name
                members:
                - userId: userId
                  email: username@example.com
                permissionSet:
                  permissions:
                  - CAN_VIEW_LOGS
                  - LIMITED_APPLICATIONS_SCOPE
                  - ACCESS_APPLICATIONS
                  - CAN_VIEW_TRACE_DETAILS
                  applicationIds:
                  - scopeId: scopeId1
                    scopeRoleId: '-102'
                  kubernetesClusterUUIDs: []
                  kubernetesNamespaceUIDs: []
                  websiteIds: []
                  mobileAppIds: []
                  syntheticTestIds: []
                  restrictedApplicationFilter:
                    label: filter name
                    tagFilterExpression:
                      type: TAG_FILTER
                      name: service.name
                      stringValue: acceptor
                      numberValue: null
                      booleanValue: null
                      key: null
                      value: acceptor
                      operator: EQUALS
                      entity: DESTINATION
                    scope: INCLUDE_NO_DOWNSTREAM
                  infraDfqFilter:
                    scopeId: ''
                    scopeRoleId: '-1'
                  actionFilter:
                    scopeId: ''
                    scopeRoleId: '-1'
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApiGroup'
          description: OK
        '404':
          description: No groups found
      security:
      - ApiKeyAuth:
        - CanConfigureTeams
      summary: Get groups of a single user
      tags:
      - Groups
      x-ibm-ahub-byok: true
      description: Returns a list of all groups a user belongs to. This includes data from these groups, the `members`, the `name` and the `Permission set`.
  /api/settings/rbac/groups/{groupId}/permissions:
    put:
      operationId: addPermissionsOnGroup
      parameters:
      - description: Id of the group to add permissions
        example: groupId
        in: path
        name: groupId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            example:
            - CAN_VIEW_SYNTHETIC_TESTS
            - CAN_VIEW_SYNTHETIC_LOCATIONS
            - CAN_CONFIGURE_AUTOMATION_ACTIONS
            schema:
              type: array
              items:
                type: string
        required: true
      responses:
        '200':
          content:
            application/json:
              example:
                id: groupId
                name: group name
                members:
                - userId: userId1
                  email: username1@example.com
                permissionSet:
                  permissions:
                  - CAN_VIEW_LOGS
                  - CAN_VIEW_SYNTHETIC_TESTS
                  - CAN_VIEW_SYNTHETIC_LOCATIONS
                  - CAN_CONFIGURE_AUTOMATION_ACTIONS
                  applicationIds: []
                  kubernetesClusterUUIDs: []
                  kubernetesNamespaceUIDs: []
                  websiteIds: []
                  mobileAppIds: []
                  syntheticTestIds: []
                  infraDfqFilter:
                    scopeId: ''
                    scopeRoleId: '-1'
                  actionFilter:
                    scopeId: ''
                    scopeRoleId: '-1'
              schema:
                $ref: '#/components/schemas/ApiGroup'
          description: OK
      security:
      - ApiKeyAuth:
        - CanConfigureTeams
      summary: Add permissions to group
      tags:
      - Groups
      x-ibm-ahub-byok: true
      description: 'Add a permission to a group. Permissions are strings associated with the group that some resources requires to fulfill requests.


        Examples of `Permissions`:


        - `ACCESS_APPLICATIONS`

        - `ACCESS_INFRASTRUCTURE`

        - `ACCESS_KUBERNETES`

        - `ACCESS_MOBILE_APPS`

        - `ACCESS_WEBSITES`

        - `CAN_CONFIGURE_AGENT_RUN_MODE`

        - `CAN_CONFIGURE_AGENTS`

        - `CAN_CONFIGURE_API_TOKENS`

        - `CAN_CONFIGURE_APPLICATIONS`

        - `CAN_CONFIGURE_AUTHENTICATION_METHODS`

        - `CAN_CONFIGURE_CUSTOM_ALERTS`

        - `CAN_CONFIGURE_EUM_APPLICATIONS`

        - `CAN_CONFIGURE_GLOBAL_ALERT_CONFIGS`

        - `CAN_CONFIGURE_GLOBAL_ALERT_PAYLOAD`

        - `CAN_CONFIGURE_INTEGRATIONS`

        - `CAN_CONFIGURE_LOG_MANAGEMENT`

        - `CAN_CONFIGURE_MOBILE_APP_MONITORING`

        - `CAN_CONFIGURE_PERSONAL_API_TOKENS`

        - `CAN_CONFIGURE_RELEASES`

        - `CAN_CONFIGURE_SERVICE_LEVEL_INDICATORS`

        - `CAN_CONFIGURE_SERVICE_MAPPING`

        - `CAN_CONFIGURE_SESSION_SETTINGS`

        - `CAN_CONFIGURE_TEAMS`

        - `CAN_CONFIGURE_USERS`

        - `CAN_CREATE_PUBLIC_CUSTOM_DASHBOARDS`

        - `CAN_EDIT_ALL_ACCESSIBLE_CUSTOM_DASHBOARDS`

        - `CAN_INSTALL_NEW_AGENTS`

        - `CAN_VIEW_ACCOUNT_AND_BILLING_INFORMATION`

        - `CAN_VIEW_AUDIT_LOG`

        - `CAN_VIEW_LOGS`

        - `CAN_VIEW_TRACE_DETAILS`

        - `LIMITED_APPLICATIONS_SCOPE`

        - `LIMITED_INFRASTRUCTURE_SCOPE`

        - `LIMITED_KUBERNETES_SCOPE`

        - `LIMITED_MOBILE_APPS_SCOPE`

        - `LIMITED_WEBSITES_SCOPE`'
  /api/settings/rbac/groups/{groupId}/users:
    put:
      operationId: addUsersToGroup
      parameters:
      - description: Id of the group to add users
        example: groupId
        in: path
        name: groupId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            example:
            - userId1
            - userId3
            schema:
              type: array
              items:
                type: string
        required: true
      responses:
        '200':
          content:
            application/json:
              example:
                id: groupId
                name: group name
                members:
                - userId: userId1
                  email: username1@example.com
                - userId: userId2
                  email: username2@example.com
                - userId: userId3
                  email: username3@example.com
                permissionSet:
                  permissions:
                  - CAN_VIEW_LOGS
                  applicationIds: []
                  kubernetesClusterUUIDs: []
                  kubernetesNamespaceUIDs: []
                  websiteIds: []
                  mobileAppIds: []
                  syntheticTestIds: []
                  infraDfqFilter:
                    scopeId: ''
                    scopeRoleId: '-1'
                  actionFilter:
                    scopeId: ''
                    scopeRoleId: '-1'
              schema:
                $ref: '#/components/schemas/ApiGroup'
          description: OK
      security:
      - ApiKeyAuth:
        - CanConfigureTeams
      summary: Add users to group
      tags:
      - Groups
      x-ibm-ahub-byok: true
      description: Add one or more users to a group. The array contains the ids of the users to be added.
  /api/settings/rbac/groups/{id}:
    delete:
      description: 'Delete the group data.

        For more information on groups please access the https://developer.ibm.com/apis/catalog/instana--instana-rest-api/Settings#groups.'
      operationId: deleteGroup
      parameters:
      - description: Id of the group to delete
        example: groupId
        in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        default:
          content:
            application/json: {}
          description: default response
      security:
      - ApiKeyAuth:
        - CanConfigureTeams
      summary: Delete group
      tags:
      - Groups
      x-ibm-ahub-byok: true
    get:
      operationId: getGroup
      parameters:
      - description: Id of the group for retrieval
        example: groupId
        in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              example:
                id: groupId
                name: group name
                members:
                - userId: userId
                  email: username@example.com
                permissionSet:
                  permissions:
                  - ACCESS_INFRASTRUCTURE
                  - LIMITED_WEBSITES_SCOPE
                  - CAN_VIEW_SYNTHETIC_TESTS
                  - CAN_VIEW_SYNTHETIC_LOCATIONS
                  - CAN_VIEW_TRACE_DETAILS
                  - CAN_CONFIGURE_AGENT_RUN_MODE
                  - CAN_CONFIGURE_AUTOMATION_ACTIONS
                  - CAN_CONFIGURE_USERS
                  - ACCESS_SYNTHETICS
                  - CAN_VIEW_LOGS
                  - LIMITED_KUBERNETES_SCOPE
                  - CAN_CONFIGURE_TEAMS
                  - CAN_VIEW_SYNTHETIC_TEST_RESULTS
                  - LIMITED_SYNTHETICS_SCOPE
                  - LIMITED_INFRASTRUCTURE_SCOPE
                  applicationIds:
                  - scopeId: scopeId1
                    scopeRoleId: '-102'
                  - scopeId: scopeId2
                    scopeRoleId: '-102'
                  - scopeId: scopeId3
                    scopeRoleId: '-102'
                  - scopeId: scopeId4
                    scopeRoleId: '-102'
                  - scopeId: scopeId5
                    scopeRoleId: '-102'
                  - scopeId: scopeId6
                    scopeRoleId: '-102'
                  kubernetesClusterUUIDs: []
                  kubernetesNamespaceUIDs: []
                  websiteIds: []
                  mobileAppIds: []
                  syntheticTestIds:
                  - scopeId: scopeId10
                    scopeRoleId: '-1'
                  restrictedApplicationFilter:
                    label: filter name
                    tagFilterExpression:
                      type: TAG_FILTER
                      name: service.name
                      stringValue: acceptor
                      numberValue: null
                      booleanValue: null
                      key: null
                      value: acceptor
                      operator: EQUALS
                      entity: DESTINATION
                    scope: INCLUDE_NO_DOWNSTREAM
                  infraDfqFilter:
                    scopeId: ''
                    scopeRoleId: '-1'
                  actionFilter:
                    scopeId: ''
                    scopeRoleId: '-1'
              schema:
                $ref: '#/components/schemas/ApiGroup'
          description: OK
      security:
      - ApiKeyAuth:
        - CanConfigureTeams
      summary: Get group
      tags:
      - Groups
      x-ibm-ahub-byok: true
      description: Returns group data, including the `Permission set`. See get groups for more details.
    put:
      operationId: updateGroup
      parameters:
      - description: Id of the group to update
        example: groupId
        in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            example:
              name: group name
              members:
              - userId: userId
                email: username@example.com
              permissionSet:
                permissions:
                - CAN_VIEW_LOGS
                applicationIds:
                - scopeId: scopeId1
                  scopeRoleId: '-102'
                kubernetesClusterUUIDs: []
                kubernetesNamespaceUIDs: []
                websiteIds: []
                mobileAppIds: []
                syntheticTestIds:
                - scopeId: scopeId10
                  scopeRoleId: '-1'
                restrictedApplicationFilter:
                  label: group name
                  tagFilterExpression:
                    type: TAG_FILTER
                    name: service.name
                    stringValue: acceptor
                    numberValue: null
                    booleanValue: null
                    key: null
                    value: acceptor
                    operator: EQUALS
                    entity: DESTINATION
                  scope: INCLUDE_NO_DOWNSTREAM
                infraDfqFilter:
                  scopeId: ''
                  scopeRoleId: '-1'
                actionFilter:
                  scopeId: ''
                  scopeRoleId: '-1'
            schema:
              $ref: '#/components/schemas/ApiGroup'
        required: true
      responses:
        '200':
          content:
            application/json:
              example:
                name: group name
                members:
                - userId: userId
                  email: username@example.com
                permissionSet:
                  permissions:
                  - CAN_VIEW_LOGS
                  applicationIds:
                  - scopeId: scopeId1
                    scopeRoleId: '-102'
                  kubernetesClusterUUIDs: []
                  kubernetesNamespaceUIDs: []
                  websiteIds: []
                  mobileAppIds: []
                  syntheticTestIds:
                  - scopeId: scopeId10
                    scopeRoleId: '-1'
                  restrictedApplicationFilter:
                    label: group name
                    tagFilterExpression:
                      type: TAG_FILTER
                      name: service.name
                      stringValue: acceptor
                      numberValue: null
                      booleanValue: null
                      key: null
                      value: acceptor
                      operator: EQUALS
                      entity: DESTINATION
                    scope: INCLUDE_NO_DOWNSTREAM
                  infraDfqFilter:
                    scopeId: ''
                    scopeRoleId: '-1'
                  actionFilter:
                    scopeId: ''
                    scopeRoleId: '-1'
              schema:
                $ref: '#/components/schemas/ApiGroup'
          description: OK
      security:
      - ApiKeyAuth:
        - CanConfigureTeams
      summary: Update group
      tags:
      - Groups
      x-ibm-ahub-byok: true
      description: 'Add a permission to a group. Permissions are strings associated with the group that some resources requires to fulfill requests.


        Examples of `Permissions`:


        - `ACCESS_APPLICATIONS`

        - `ACCESS_INFRASTRUCTURE`

        - `ACCESS_KUBERNETES`

        - `ACCESS_MOBILE_APPS`

        - `ACCESS_WEBSITES`

        - `CAN_CONFIGURE_AGENT_RUN_MODE`

        - `CAN_CONFIGURE_AGENTS`

        - `CAN_CONFIGURE_API_TOKENS`

        - `CAN_CONFIGURE_APPLICATIONS`

        - `CAN_CONFIGURE_AUTHENTICATION_METHODS`

        - `CAN_CONFIGURE_CUSTOM_ALERTS`

        - `CAN_CONFIGURE_EUM_APPLICATIONS`

        - `CAN_CONFIGURE_GLOBAL_ALERT_CONFIGS`

        - `CAN_CONFIGURE_GLOBAL_ALERT_PAYLOAD`

        - `CAN_CONFIGURE_INTEGRATIONS`

        - `CAN_CONFIGURE_LOG_MANAGEMENT`

        - `CAN_CONFIGURE_MOBILE_APP_MONITORING`

        - `CAN_CONFIGURE_PERSONAL_API_TOKENS`

        - `CAN_CONFIGURE_RELEASES`

        - `CAN_CONFIGURE_SERVICE_LEVEL_INDICATORS`

        - `CAN_CONFIGURE_SERVICE_MAPPING`

        - `CAN_CONFIGURE_SESSION_SETTINGS`

        - `CAN_CONFIGURE_TEAMS`

        - `CAN_CONFIGURE_USERS`

        - `CAN_CREATE_PUBLIC_CUSTOM_DASHBOARDS`

        - `CAN_EDIT_ALL_ACCESSIBLE_CUSTOM_DASHBOARDS`

        - `CAN_INSTALL_NEW_AGENTS`

        - `CAN_VIEW_ACCOUNT_AND_BILLING_INFORMATION`

        - `CAN_VIEW_AUDIT_LOG`

        - `CAN_VIEW_LOGS`

        - `CAN_VIEW_TRACE_DETAILS`

        - `LIMITED_APPLICATIONS_SCOPE`

        - `LIMITED_INFRASTRUCTURE_SCOPE`

        - `LIMITED_KUBERNETES_SCOPE`

        - `LIMITED_MOBILE_APPS_SCOPE`

        - `LIMITED_WEBSITES_SCOPE`'
  /api/settings/rbac/groups/{id}/user/{userId}:
    delete:
      description: 'Remove the user from a group.

        For more information on groups please access the https://developer.ibm.com/apis/catalog/instana--instana-rest-api/Settings#groups.'
      operationId: removeUserFromGroup
      parameters:
      - description: Id of the group to remove user from
        example: groupId
        in: path
        name: id
        required: true
        schema:
          type: string
      - description: Id of the user to remove
        example: userId
        in: path
        name: userId
        required: true
        schema:
          type: string
      responses:
        default:
          content:
            application/json: {}
          description: default response
      security:
      - ApiKeyAuth:
        - CanConfigureTeams
      summary: Remove user from group
      tags:
      - Groups
      x-ibm-ahub-byok: true
  /api/settings/rbac/mappings:
    get:
      operationId: getGroupMappings
      responses:
        '200':
          content:
            application/json:
              example:
              - id: mappingId
                key: roles
                value: analyst
                groupId: '-3'
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GroupMapping'
          description: OK
        '404':
          description: No group mapping found
      security:
      - ApiKeyAuth:
        - CanConfigureAuthenticationMethods
      summary: Get all group mappings
      tags:
      - Groups
      x-ibm-ahub-byok: true
      description: 'If mappings between groups on the identity provider (LDAP, OIDC, SAML) and Instana groups where configured, this will return a list of those mappings.


        This can be configured through the api or on Instana graphical user interface at Settings > Authentication > IDENTITY PROVIDERS > Group Mapping.'
    post:
      operationId: createGroupMapping
      requestBody:
        content:
          application/json:
            example:
              key: roles
              value: analyst
              groupId: '-3'
            schema:
              $ref: '#/components/schemas/GroupMapping'
        required: true
      responses:
        '200':
          content:
            application/json:
              example:
                id: mappingId
                key: roles
                value: analyst
                groupId: '-3'
              schema:
                $ref: '#/components/schemas/GroupMapping'
          description: OK
      security:
      - ApiKeyAuth:
        - CanConfigureAuthenticationMethods
      summary: Create group mapping
      tags:
      - Groups
      x-ibm-ahub-byok: true
      description: 'Creates a mapping between a group from the IdP (LDAP, OIDC, SAML) and an Instana group.


        If the IdP is configured and mappings are enabled, the `key` `value` pairs a user sent by the idp will be evaluated every time this user logs in.


        If they match the mapping, the user will be assigned to the group corresponding to the `groupId`.


        Inside the payload, the `id` for the mapping is ignored, and instead, Instana generates a new id.'
  /api/settings/rbac/mappings/delete:
    put:
      operationId: deleteGroupMappings
      requestBody:
        content:
          application/json:
            example:
            - firstid
            - secondid
            schema:
              type: string
        required: true
      responses:
        '204':
          description: OK
        '422':
          description: invalid request
      security:
      - ApiKeyAuth:
        - CanConfigureAuthenticationMethods
      summary: Delete multiple group mappings
      tags:
      - Groups
      x-ibm-ahub-byok: true
  /api/settings/rbac/mappings/identityProvider/restrictEmptyIdpGroups:
    get:
      operationId: getIdentityProviderPatch
      responses:
        '200':
          content:
            application/json:
              example:
                restrictEmptyIdpGroups: false
              schema:
                $ref: '#/components/schemas/IdentityProviderPatch'
          description: OK
        '404':
          description: No group mapping restriction found
      security:
      - ApiKeyAuth:
        - CanConfigureAuthenticationMethods
      summary: Check user restrictions for empty Idp group mapping
      tags:
      - Groups
      x-ibm-ahub-byok: true
      description: Returns `RestrictEmptyIdpGroups` value indicating if access is denied for empty Idp group mapping. `RestrictEmptyIdpGroups = true` indicates that the tenant is locked and only those users are allowed access that have at least one working mapping rule applied to them during the login process.
    put:
      operationId: updateIdentityProvider
      requestBody:
        content:
          application/json:
            example:
              restrictEmptyIdpGroups: true
            schema:
              $ref: '#/components/schemas/IdentityProviderPatch'
        required: true
      responses:
        default:
          content:
            application/json: {}
          description: default response
      security:
      - ApiKeyAuth:
        - CanConfigureAuthenticationMethods
      summary: Allow/Restrict users with empty Idp group mapping
      tags:
      - Groups
      x-ibm-ahub-byok: true
      description: Set the RestrictEmptyIdpGroups value as true/false. See Check user restrictions for empty Idp group mapping for more details.
  /api/settings/rbac/mappings/overview:
    get:
      operationId: getGroupMappingsOverview
      responses:
        '200':
          content:
            application/json:
              example:
              - id: mappingId
                key: roles
                value: analyst
                role: default
                team: testing
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GroupMappingOverview'
          description: OK
        '404':
          description: No group mapping overviews found
      security:
      - ApiKeyAuth:
        - CanConfigureAuthenticationMethods
      summary: Get all group mappings overview
      tags:
      - Groups
      x-ibm-ahub-byok: true
  /api/settings/rbac/mappings/{id}:
    delete:
      operationId: deleteGroupMapping
      parameters:
      - description: Id of the group mapping to delete
        example: mappingId
        in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        default:
          content:
            application/json: {}
          description: default response
      security:
      - ApiKeyAuth:
        - CanConfigureAuthenticationMethods
      summary: Delete group mapping
      tags:
      - Groups
      x-ibm-ahub-byok: true
    get:
      operationId: getGroupMapping
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              example:
                id: mappingId
                key: roles
                value: analyst
                groupId: '-3'
              schema:
                $ref: '#/components/schemas/GroupMapping'
          description: OK
        '404':
          description: No group mapping found
      security:
      - ApiKeyAuth:
        - CanConfigureAuthenticationMethods
      summary: Get group mapping
      tags:
      - Groups
      x-ibm-ahub-byok: true
    put:
      operationId: updateGroupMapping
      parameters:
      - description: Id of the group mapping to update
        example: mappingId
        in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            example:
              id: mappingId
              key: roles
              value: analyst
              groupId: '-3'
            schema:
              $ref: '#/components/schemas/GroupMapping'
        required: true
      responses:
        '200':
          content:
            application/json:
              example:
                id: mappingId
                key: roles
                value: analyst
                groupId: '-3'
              schema:
                $ref: '#/components/schemas/GroupMapping'
          description: OK
      security:
      - ApiKeyAuth:
        - CanConfigureAuthenticationMethods
      summary: Update group mapping
      tags:
      - Groups
      x-ibm-ahub-byok: true
      description: See creating group mapping
components:
  schemas:
    ApiPermissionSet:
      type: object
      properties:
        actionFilter:
          $ref: '#/components/schemas/ScopeBinding'
        applicationIds:
          type: array
          items:
            $ref: '#/components/schemas/ScopeBinding'
          maxItems: 1024
          minItems: 0
          uniqueItems: true
        businessPerspectiveIds:
          type: array
          items:
            $ref: '#/components/schemas/ScopeBinding'
          maxItems: 1024
          minItems: 0
          uniqueItems: true
        infraDfqFilter:
          $ref: '#/components/schemas/ScopeBinding'
        kubernetesClusterUUIDs:
          type: array
          items:
            $ref: '#/components/schemas/ScopeBinding'
          maxItems: 1024
          minItems: 0
          uniqueItems: true
        kubernetesNamespaceUIDs:
          type: array
          items:
            $ref: '#/components/schemas/ScopeBinding'
          maxItems: 1024
          minItems: 0
          uniqueItems: true
        mobileAppIds:
          type: array
          items:
            $ref: '#/components/schemas/ScopeBinding'
          maxItems: 1024
          minItems: 0
          uniqueItems: true
        permissions:
          type: array
          items:
            type: string
          maxItems: 1024
          minItems: 0
          uniqueItems: true
        restrictedApplicationFilter:
          $ref: '#/components/schemas/ApiRestrictedApplicationFilter'
        sloIds:
          type: array
          items:
            $ref: '#/components/schemas/ScopeBinding'
          maxItems: 1024
          minItems: 0
          uniqueItems: true
        syntheticCredentialKeys:
          type: array
          items:
            $ref: '#/components/schemas/ScopeBinding'
          maxItems: 1024
          minItems: 0
          uniqueItems: true
        syntheticTestIds:
          type: array
          items:
            $ref: '#/components/schemas/ScopeBinding'
          maxItems: 1024
          minItems: 0
          uniqueItems: true
        websiteIds:
          type: array
          items:
            $ref: '#/components/schemas/ScopeBinding'
          maxItems: 1024
          minItems: 0
          uniqueItems: true
      required:
      - applicationIds
      - businessPerspectiveIds
      - infraDfqFilter
      - kubernetesClusterUUIDs
      - kubernetesNamespaceUIDs
      - mobileAppIds
      - permissions
      - sloIds
      - syntheticCredentialKeys
      - syntheticTestIds
      - websiteIds
    ApiMember:
      type: object
      properties:
        email:
          type: string
        name:
          type: string
        userId:
          type: string
      required:
      - userId
    GroupMapping:
      type: object
      properties:
        groupId:
          type: string
        id:
          type: string
          maxLength: 64
          minLength: 0
        key:
          type: string
          maxLength: 65536
          minLength: 0
        teamId:
          type: string
          maxLength: 64
          minLength: 5
        value:
          type: string
          maxLength: 65536
          minLength: 0
      required:
      - groupId
      - key
      - value
    ScopeBinding:
      type: object
      properties:
        scopeId:
          type: string
          maxLength: 64
          minLength: 0
        scopeRoleId:
          type: string
          maxLength: 64
          minLength: 0
    ApiGroup:
      type: object
      properties:
        id:
          type: string
          maxLength: 64
          minLength: 0
        members:
          type: array
          items:
            $ref: '#/components/schemas/ApiMember'
          uniqueItems: true
        name:
          type: string
        permissionSet:
          $ref: '#/components/schemas/ApiPermissionSet'
      required:
      - id
      - members
      - name
      - permissionSet
    TagFilterExpressionElement:
      type: object
      description: Boolean expression of tag filters to define the scope of relevant calls.
      discriminator:
        mapping:
          EXPRESSION: '#/components/schemas/TagFilterExpression'
          TAG_FILTER: '#/components/schemas/TagFilter'
        propertyName: type
      properties:
        type:
          type: string
      required:
      - type
    ApiRestrictedApplicationFilter:
      type: object
      properties:
        label:
          type: string
        restrictingApplicationId:
          type: string
        scope:
          type: string
          enum:
          - INCLUDE_NO_DOWNSTREAM
          - INCLUDE_IMMEDIATE_DOWNSTREAM_DATABASE_AND_MESSAGING
          - INCLUDE_ALL_DOWNSTREAM
        tagFilterExpression:
          $ref: '#/components/schemas/TagFilterExpressionElement'
    GroupMappingOverview:
      type: object
      properties:
        id:
          type: string
        key:
          type: string
        role:
          type: string
        team:
          type: string
        value:
          type: string
    IdentityProviderPatch:
      type: object
      properties:
        restrictEmptyIdpGroups:
          type: boolean
    ApiCreateGroup:
      type: object
      properties:
        members:
          type: array
          items:
            $ref: '#/components/schemas/ApiMember'
          uniqueItems: true
        name:
          type: string
        permissionSet:
          $ref: '#/components/schemas/ApiPermissionSet'
      required:
      - members
      - name
      - permissionSet
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: authorization
      type: apiKey
      description: "## Example\n\n```bash\ncurl --request GET \\\n  --url https://test-instana.instana.io/api/application-monitoring/catalog/metrics \\\n  --header 'authorization: apiToken xxxxxxxxxxxxxxxx'\n```\n"
x-tagGroups:
- name: Websites & Mobile Apps
  tags:
  - Website Metrics
  - Website Catalog
  - Website Analyze
  - Website Configuration
  - Mobile App Metrics
  - Mobile App Catalog
  - Mobile App Analyze
  - Mobile App Configuration
  - End User Monitoring
- name: Applications
  tags:
  - Application Metrics
  - Application Resources
  - Application Catalog
  - Application Analyze
  - Application Settings
  - Application Topology
  - Application Alert Configuration
  - Global Application Alert Configuration
- name: Infrastructure
  tags:
  - Infrastructure Analyze
  - Infrastructure Metrics
  - Infrastructure Resources
  - Infrastructure Catalog
  - Infrastructure Topology
- name: Logging
  tags:
  - Logging Analyze
- name: Synthetic Monitoring
  tags:
  - Synthetic Catalog
  - Synthetic Metrics
  - Synthetic Settings
  - Synthetic Test Playback Results
  - Synthetic Alert Configuration
- name: Logs
  tags:
  - Log Alert Configuration
- name: Events
  tags:
  - Events
  - Event Settings
- name: Automation
  tags:
  - Action Catalog
  - Action History
  - Policies
- name: Service Levels
  tags:
  - SLI Settings
  - SLI Report
  - Apdex Settings
  - Apdex Report
  - Service Levels Objective(SLO) Configurations
  - Service Levels Objective(SLO) Report
  - Service Levels Alert Configuration
  - SLO Correction Configurations
  - SLO Correction Windows
- name: AI Management
  tags:
  - AI Management
- name: Settings
  tags:
  - Custom Dashboards
  - User
  - Groups
  - Teams
  - Roles
  - Audit Log
  - API Token
  - Maintenance Configuration
  - Synthetic Calls
  - Session Settings
  - Automation Settings
  - Authentication
- name: Open Beta Features
  tags:
  - Infrastructure Analyze
- name: Closed Beta Features
  tags:
  - Infrastructure Alert Configuration
- name: Instana
  tags:
  - Releases
  - Host Agent
  - Health
  - Usage
