openapi: 3.2.0
info:
  contact:
    email: support@instana.com
    name: © Instana
    url: http://instana.com
  termsOfService: https://www.instana.com/terms-of-use/
  title: Instana REST API documentation Roles API
  version: 1.307.1417
  x-ibm-ahub-try: true
  x-logo:
    altText: instana logo
    backgroundColor: '#FAFBFC'
    url: header-logo.svg
  description: Searching for answers and best pratices?
servers:
- description: Instana Backend
  url: https://{unit}-{tenant}.instana.io
  variables:
    tenant:
      default: tenant
      description: Customer tenant unit
    unit:
      default: unit
      description: Customer tenant name
- description: Instana Self-Hosted Backend
  url: https://{domain}
  variables:
    domain:
      default: example.com
      description: Customer Self-Hosted domain
tags:
- name: Roles
paths:
  /api/settings/rbac/roles:
    get:
      description: Retrieve all roles for the current tenant unit.
      operationId: getRoles
      responses:
        '200':
          content:
            application/json:
              example:
              - id: role-1
                name: Administrator
                members:
                - userId: user-1
                  email: admin@example.com
                  name: Admin User
                - userId: user-2
                  email: manager@example.com
                  name: Manager User
                permissions:
                - CAN_CONFIGURE_APPLICATIONS
                - CAN_CONFIGURE_EVENTS
                - CAN_CONFIGURE_INFRASTRUCTURE
                - CAN_CONFIGURE_TEAMS
              - id: role-2
                name: Developer
                members:
                - userId: user-3
                  email: dev1@example.com
                  name: Developer One
                - userId: user-4
                  email: dev2@example.com
                  name: Developer Two
                permissions:
                - CAN_VIEW_APPLICATIONS
                - CAN_VIEW_EVENTS
                - CAN_VIEW_INFRASTRUCTURE
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApiRole'
          description: OK
        '404':
          description: No roles found
      security:
      - ApiKeyAuth:
        - CanConfigureTeams
      summary: Get all roles
      tags:
      - Roles
      x-ibm-ahub-byok: true
    post:
      description: Create a new role.
      operationId: createRole
      requestBody:
        content:
          application/json:
            example:
              name: New Role
              members:
              - userId: user-5
                email: newuser@example.com
                name: New User
              permissions:
              - CAN_VIEW_APPLICATIONS
              - CAN_VIEW_EVENTS
            schema:
              $ref: '#/components/schemas/ApiCreateRole'
        description: Role to create
        required: true
      responses:
        '200':
          content:
            application/json:
              example:
                id: role-3
                name: New Role
                members:
                - userId: user-5
                  email: newuser@example.com
                  name: New User
                permissions:
                - CAN_VIEW_APPLICATIONS
                - CAN_VIEW_EVENTS
              schema:
                $ref: '#/components/schemas/ApiRole'
          description: OK
      security:
      - ApiKeyAuth:
        - CanConfigureTeams
      summary: Create role
      tags:
      - Roles
      x-ibm-ahub-byok: true
  /api/settings/rbac/roles/{id}:
    delete:
      description: Delete a role by ID.
      operationId: deleteRole
      parameters:
      - description: Id of the role to delete
        example: roleId
        in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '204':
          description: Role successfully deleted
        '404':
          description: Role not found
      security:
      - ApiKeyAuth:
        - CanConfigureTeams
      summary: Delete role
      tags:
      - Roles
      x-ibm-ahub-byok: true
    get:
      description: Retrieve a specific role by its ID.
      operationId: getRole
      parameters:
      - description: Id of the role for retrieval
        example: roleId
        in: path
        name: id
        required: true
        schema:
          type: string
      - in: query
        name: includeTeamUsage
        schema:
          type: boolean
      responses:
        '200':
          content:
            application/json:
              example:
                id: role-1
                name: Administrator
                members:
                - userId: user-1
                  email: admin@example.com
                  name: Admin User
                - userId: user-2
                  email: manager@example.com
                  name: Manager User
                permissions:
                - CAN_CONFIGURE_APPLICATIONS
                - CAN_CONFIGURE_EVENTS
                - CAN_CONFIGURE_INFRASTRUCTURE
                - CAN_CONFIGURE_TEAMS
              schema:
                $ref: '#/components/schemas/ApiRole'
          description: OK
        '404':
          description: Role not found
      security:
      - ApiKeyAuth:
        - CanConfigureTeams
      summary: Get role by ID
      tags:
      - Roles
      x-ibm-ahub-byok: true
    put:
      description: Update an existing role by ID.
      operationId: updateRole
      parameters:
      - description: Id of the role to update
        example: roleId
        in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            example:
              id: role-2
              name: Updated Developer Role
              members:
              - userId: user-3
                email: dev1@example.com
                name: Developer One
              - userId: user-4
                email: dev2@example.com
                name: Developer Two
              - userId: user-6
                email: dev3@example.com
                name: Developer Three
              permissions:
              - CAN_VIEW_APPLICATIONS
              - CAN_VIEW_EVENTS
              - CAN_VIEW_INFRASTRUCTURE
              - CAN_CONFIGURE_APPLICATIONS
            schema:
              $ref: '#/components/schemas/ApiRole'
        description: Updated role data
        required: true
      responses:
        '200':
          content:
            application/json:
              example:
                id: role-2
                name: Updated Developer Role
                members:
                - userId: user-3
                  email: dev1@example.com
                  name: Developer One
                - userId: user-4
                  email: dev2@example.com
                  name: Developer Two
                - userId: user-6
                  email: dev3@example.com
                  name: Developer Three
                permissions:
                - CAN_VIEW_APPLICATIONS
                - CAN_VIEW_EVENTS
                - CAN_VIEW_INFRASTRUCTURE
                - CAN_CONFIGURE_APPLICATIONS
              schema:
                $ref: '#/components/schemas/ApiRole'
          description: OK
        '404':
          description: Role not found
      security:
      - ApiKeyAuth:
        - CanConfigureTeams
      summary: Update role
      tags:
      - Roles
      x-ibm-ahub-byok: true
components:
  schemas:
    ApiCreateRole:
      type: object
      properties:
        members:
          type: array
          items:
            $ref: '#/components/schemas/ApiMember'
          uniqueItems: true
        name:
          type: string
        permissions:
          type: array
          items:
            type: string
          maxItems: 1024
          minItems: 0
          uniqueItems: true
      required:
      - name
    ApiRole:
      type: object
      properties:
        id:
          type: string
        members:
          type: array
          items:
            $ref: '#/components/schemas/ApiMember'
          uniqueItems: true
        name:
          type: string
        permissions:
          type: array
          items:
            type: string
          uniqueItems: true
      required:
      - id
      - members
      - name
      - permissions
    ApiMember:
      type: object
      properties:
        email:
          type: string
        name:
          type: string
        userId:
          type: string
      required:
      - userId
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: authorization
      type: apiKey
      description: "## Example\n\n```bash\ncurl --request GET \\\n  --url https://test-instana.instana.io/api/application-monitoring/catalog/metrics \\\n  --header 'authorization: apiToken xxxxxxxxxxxxxxxx'\n```\n"
x-tagGroups:
- name: Websites & Mobile Apps
  tags:
  - Website Metrics
  - Website Catalog
  - Website Analyze
  - Website Configuration
  - Mobile App Metrics
  - Mobile App Catalog
  - Mobile App Analyze
  - Mobile App Configuration
  - End User Monitoring
- name: Applications
  tags:
  - Application Metrics
  - Application Resources
  - Application Catalog
  - Application Analyze
  - Application Settings
  - Application Topology
  - Application Alert Configuration
  - Global Application Alert Configuration
- name: Infrastructure
  tags:
  - Infrastructure Analyze
  - Infrastructure Metrics
  - Infrastructure Resources
  - Infrastructure Catalog
  - Infrastructure Topology
- name: Logging
  tags:
  - Logging Analyze
- name: Synthetic Monitoring
  tags:
  - Synthetic Catalog
  - Synthetic Metrics
  - Synthetic Settings
  - Synthetic Test Playback Results
  - Synthetic Alert Configuration
- name: Logs
  tags:
  - Log Alert Configuration
- name: Events
  tags:
  - Events
  - Event Settings
- name: Automation
  tags:
  - Action Catalog
  - Action History
  - Policies
- name: Service Levels
  tags:
  - SLI Settings
  - SLI Report
  - Apdex Settings
  - Apdex Report
  - Service Levels Objective(SLO) Configurations
  - Service Levels Objective(SLO) Report
  - Service Levels Alert Configuration
  - SLO Correction Configurations
  - SLO Correction Windows
- name: AI Management
  tags:
  - AI Management
- name: Settings
  tags:
  - Custom Dashboards
  - User
  - Groups
  - Teams
  - Roles
  - Audit Log
  - API Token
  - Maintenance Configuration
  - Synthetic Calls
  - Session Settings
  - Automation Settings
  - Authentication
- name: Open Beta Features
  tags:
  - Infrastructure Analyze
- name: Closed Beta Features
  tags:
  - Infrastructure Alert Configuration
- name: Instana
  tags:
  - Releases
  - Host Agent
  - Health
  - Usage
