openapi: 3.2.0
info:
  contact:
    email: support@instana.com
    name: © Instana
    url: http://instana.com
  termsOfService: https://www.instana.com/terms-of-use/
  title: Instana REST API documentation Application Metrics API
  version: 1.307.1417
  x-ibm-ahub-try: true
  x-logo:
    altText: instana logo
    backgroundColor: '#FAFBFC'
    url: header-logo.svg
  description: Searching for answers and best pratices?
servers:
- description: Instana Backend
  url: https://{unit}-{tenant}.instana.io
  variables:
    tenant:
      default: tenant
      description: Customer tenant unit
    unit:
      default: unit
      description: Customer tenant name
- description: Instana Self-Hosted Backend
  url: https://{domain}
  variables:
    domain:
      default: example.com
      description: Customer Self-Hosted domain
tags:
- name: Application Metrics
  description: The endpoints of this group retrieve the metrics for defined applications, discovered services and endpoints.
paths:
  /api/application-monitoring/metrics/applications:
    post:
      description: 'Use this API endpoint if one wants to retrieve one or more supported aggregation of supported metrics for an Application Perspective.

        For eg: retrieve `MEAN` aggregation of `latency` metric for an Application Perspective `app`.

        For more information on supported metrics, refer `Get Metric catalog`.


        For more information on Application Metrics please access the https://developer.ibm.com/apis/catalog/instana--instana-rest-api/Applications#application-metrics.'
      operationId: getApplicationMetrics
      parameters:
      - description: If enabled, fill the missing data points in the metric result with timestamp and value 0.
        in: query
        name: fillTimeSeries
        schema:
          type: boolean
      requestBody:
        content:
          application/json:
            examples:
              metrics/applications:
                description: 'Attribute in "order by" should

                  be provided in "metrics" as well

                  '
                value:
                  metrics:
                  - aggregation: MEAN
                    metric: latency
                  order:
                    by: latency
                    direction: DESC
                  pagination:
                    page: 1
                    pageSize: 1
                  timeFrame:
                    to: 1646037122400
                    windowSize: 3600000
            schema:
              $ref: '#/components/schemas/GetApplications'
      responses:
        '200':
          content:
            application/json:
              example:
                items:
                - application:
                    id: Jv83WpUmSKiiCWIpi-reSQ
                    label: demoApp
                    boundaryScope: ALL
                    entityType: APPLICATION
                  metrics:
                    latency.mean:
                    - - 1669190580000
                      - 4
                page: 1
                pageSize: 1
                totalHits: 1616
                adjustedTimeframe:
                  windowSize: 3600000
                  to: 1646037120000
              schema:
                $ref: '#/components/schemas/ApplicationMetricResult'
          description: OK
      security:
      - ApiKeyAuth:
        - Default
      summary: Get Application Metrics
      tags:
      - Application Metrics
      x-ibm-ahub-byok: true
  /api/application-monitoring/metrics/endpoints:
    post:
      description: 'Use this API endpoint if one wants to retrieve one or more supported aggregation of supported metrics for an Endpoint.

        For eg: retrieve `MEAN` aggregation of `latency` metric for an Endpoint `GET /api/foo`.

        For more information on supported metrics, refer `Get Metric catalog`.


        For more information on Application Metrics please access the https://developer.ibm.com/apis/catalog/instana--instana-rest-api/Applications#application-metrics.'
      operationId: getEndpointsMetrics
      parameters:
      - description: If enabled, fill the missing data points in the metric result with timestamp and value 0.
        in: query
        name: fillTimeSeries
        schema:
          type: boolean
      requestBody:
        content:
          application/json:
            examples:
              metrics/endpoints:
                description: 'Order by is supported for following attributes: endpointLabel or valid metrics if provided such as latency.mean

                  '
                value:
                  applicationBoundaryScope: ALL
                  endpointId: murzTwzJlGyqc_CFtEKx8INVCfY
                  excludeSynthetic: true
                  metrics:
                  - aggregation: MEAN
                    metric: latency
                  order:
                    by: latency.mean
                    direction: ASC
                  pagination:
                    page: 1
                    pageSize: 1
                  timeFrame:
                    to: 1669190589000
                    windowSize: 3600000
            schema:
              $ref: '#/components/schemas/GetEndpoints'
      responses:
        '200':
          content:
            application/json:
              example:
                items:
                - endpoint:
                    id: murzTwzJlGyqc_CFtEKx8INVCfY
                    label: robot-shop
                    type: MESSAGING
                    serviceId: 05b145cfb6fbc24d08a8e01155c0aa2bf8460c87
                    technologies:
                    - golangRuntimePlatform
                    - kubernetesService
                    syntheticType: NON_SYNTHETIC
                    synthetic: false
                    entityType: ENDPOINT
                  metrics:
                    latency.mean:
                    - - 1669190580000
                      - 2434.5625
                page: 1
                pageSize: 1
                totalHits: 1
                adjustedTimeframe:
                  windowSize: 3600000
                  to: 1669190580000
              schema:
                $ref: '#/components/schemas/EndpointMetricResult'
          description: OK
      security:
      - ApiKeyAuth:
        - Default
      summary: Get Endpoint metrics
      tags:
      - Application Metrics
      x-ibm-ahub-byok: true
  /api/application-monitoring/metrics/services:
    post:
      description: 'Use this API endpoint if one wants to retrieve one or more supported aggregation of supported metrics for a Service.

        For eg: retrieve `MEAN` aggregation of `latency` metric for a Service `payment`.

        For more information on supported metrics, refer `Get Metric catalog`.


        For more information on Application Metrics please access the https://developer.ibm.com/apis/catalog/instana--instana-rest-api/Applications#application-metrics.'
      operationId: getServicesMetrics
      parameters:
      - description: If enabled, fill the missing data points in the metric result with timestamp and value 0.
        in: query
        name: fillTimeSeries
        schema:
          type: boolean
      - in: query
        name: includeSnapshotIds
        schema:
          type: boolean
      requestBody:
        content:
          application/json:
            examples:
              metrics/services:
                description: "Order by is supported for following attributes: types, technologies, serviceLabel and\n valid metrics if provided such as latency.mean\n"
                value:
                  applicationBoundaryScope: ALL
                  contextScope: NONE
                  metrics:
                  - aggregation: mean
                    metric: latency
                  order:
                    by: latency.mean
                    direction: DESC
                  pagination:
                    page: 1
                    pageSize: 1
                  serviceId: c467ca0fa21477fee3cde75a140b2963307388a7
                  technologies:
                  - springbootApplicationContainer
                  timeFrame:
                    to: 1669190589000
                    windowSize: 3600000
            schema:
              $ref: '#/components/schemas/GetServices'
      responses:
        '200':
          content:
            application/json:
              example:
                items:
                - service:
                    id: c467ca0fa21477fee3cde75a140b2963307388a7
                    label: discount
                    types:
                    - HTTP
                    technologies:
                    - springbootApplicationContainer
                    snapshotIds: []
                    entityType: SERVICE
                  metrics:
                    endpoints.distinct_count:
                    - - 1669190580000
                      - 4
                page: 1
                pageSize: 1
                totalHits: 1
                adjustedTimeframe:
                  windowSize: 3600000
                  to: 1669190580000
              schema:
                $ref: '#/components/schemas/ServiceMetricResult'
          description: OK
      security:
      - ApiKeyAuth:
        - Default
      summary: Get Service metrics
      tags:
      - Application Metrics
      x-ibm-ahub-byok: true
  /api/application-monitoring/v2/metrics:
    post:
      description: 'Use this API endpoint if one wants to retrieve one or more supported aggregation of supported metrics for a combination of entities.

        For eg: retrieve `MEAN` aggregation of `latency` metric for an Endpoint `GET /api/foo`, Service `payment` and Application Perspective `app`.

        Consider this API endpoint an upgraded version of `Get Application Metrics`, `Get Endpoint metrics` and `Get Service metrics`.

        For more information on supported metrics, refer `Get Metric catalog`.


        For more information on Application Metrics please access the https://developer.ibm.com/apis/catalog/instana--instana-rest-api/Applications#application-metrics.'
      operationId: getApplicationDataMetricsV2
      requestBody:
        content:
          application/json:
            example:
              includeInternal: true
              includeSynthetic: true
              metrics:
              - aggregation: MEAN
                metric: latency
              tagFilterExpression:
                type: TAG_FILTER
                name: service.name
                operator: EQUALS
                entity: DESTINATION
                value: warehouse
              timeFrame:
                to: 1669190589000
                windowSize: 3600000
            schema:
              $ref: '#/components/schemas/GetApplicationMetrics'
      responses:
        '200':
          content:
            application/json:
              example:
                metrics:
                  latency.mean:
                  - - 1669190580000
                    - 106.85055708882756
                adjustedTimeframe:
                  windowSize: 3600000
                  to: 1669190580000
              schema:
                $ref: '#/components/schemas/MetricAPIResult'
          description: OK
      security:
      - ApiKeyAuth:
        - Default
      summary: Get Application Data Metrics
      tags:
      - Application Metrics
      x-ibm-ahub-byok: true
components:
  schemas:
    GetApplications:
      type: object
      properties:
        applicationBoundaryScope:
          type: string
          description: "Use when querying calls of an application:\n `INBOUND`: only inbound calls \n `ALL`: all the calls to that application (inbound + internal)"
          enum:
          - ALL
          - INBOUND
        applicationId:
          type: string
          description: 'An Instana generated unique identifier for an Application. If specified, the list of results will be filtered for the specified Application ID. Eg: `Av62RoIKQv-A3n6DbMQh9g`.

            One can see the application id from Instana UI by going to an Application Perspective page. In the URL, there will be `appId=Av62RoIKQv-A3n6DbMQh9g`.

            Alternatively, one can use `Get applications` API endpoint to get the application id in `id` parameter.

            '
          maxLength: 64
          minLength: 0
        endpointId:
          type: string
          description: 'An Instana generated unique identifier for an Endpoint. If specified, the list of results will be filtered for the specified Endpoint ID. Eg `NCRq5oYnan5x-PkdTPQwLLUdu5M`.

            One can see the endpoint id from Instana UI by going to an Endpoint page. In the URL, there will be `endpointId=NCRq5oYnan5x-PkdTPQwLLUdu5M`.

            Alternatively, one can use `Get endpoints` API endpoint to get the endpoint id in `id` parameter.

            '
          maxLength: 64
          minLength: 0
        endpointTypes:
          type: array
          items:
            type: string
            enum:
            - UNDEFINED
            - RPC
            - EVENT
            - GRAPHQL
            - BATCH
            - SHELL
            - HTTP
            - SDK
            - OPENTELEMETRY
            - INTERNAL
            - DATABASE
            - MESSAGING
            - PAGE
            - PAGE_RESOURCE
          uniqueItems: true
          writeOnly: true
        metrics:
          type: array
          description: 'A list of objects each of which defines a metric and the (statistical) aggregation -- MEAN, SUM, MAX, etc -- that should be used to summarize it for the defined time frame. Eg: `[{ ''metric'': ''latency'', ''aggregation'': ''MEAN''}]`. To know more about supported metrics and its aggregation, See `Get Metric catalog`.'
          items:
            $ref: '#/components/schemas/AppDataMetricConfiguration'
          maxItems: 5
          minItems: 1
        nameFilter:
          type: string
          description: 'filter by name with `contains` semantic. Eg: Let''s say there are 2 names `app1` and `app2`, you can set `app`` here to include the two names'
          maxLength: 256
          minLength: 0
        order:
          $ref: '#/components/schemas/Order'
        pagination:
          $ref: '#/components/schemas/Pagination'
        serviceId:
          type: string
          description: 'An Instana generated unique identifier for a Service. If specified, the list of results will be filtered for the specified Service ID. Eg: `3feb3dcd206c166ef2b41c707e0cd38d7cd325aa`.

            One can see the service id from Instana UI by going to a Service page. In the URL, there will be `serviceId=3feb3dcd206c166ef2b41c707e0cd38d7cd325aa`.

            Alternatively, one can use `Get services` API endpoint to get the service id in `id` parameter.

            '
          maxLength: 64
          minLength: 0
        technologies:
          type: array
          items:
            type: string
          uniqueItems: true
          writeOnly: true
        timeFrame:
          $ref: '#/components/schemas/TimeFrame'
      required:
      - metrics
    ApplicationMetricResult:
      type: object
      properties:
        adjustedTimeframe:
          $ref: '#/components/schemas/AdjustedTimeframe'
        items:
          type: array
          items:
            $ref: '#/components/schemas/ApplicationItem'
        page:
          type: integer
          format: int32
          description: Page Number
          minimum: 1
        pageSize:
          type: integer
          format: int32
          minimum: 1
        totalHits:
          type: integer
          format: int64
          minimum: 0
      required:
      - items
    AdjustedTimeframe:
      type: object
      description: 'Time frame provided in API request is slightly adjusted in response for faster API response.

        For example, In request payload, if timeframe is 08:03 - 14:03, which is a 6 hour window size. It is adjusted to 08:05 - 14:00

        Another example, In request payload, if timeframe is 08:20 - 08:20 (next day) which is a 24h window size. It is adjusted to 08:30 - 08:00 (next day)

        '
      properties:
        to:
          type: integer
          format: int64
          description: 'end of timeframe expressed as the Unix epoch time in milliseconds. Eg: `ISO 8601` standard time `2024-06-27T05:05:55.615Z` can be represented as `1719464755615` in Unix epoch time in milliseconds.'
        windowSize:
          type: integer
          format: int64
          description: windowSize in milliseconds
          minimum: 0
      required:
      - to
    EndpointItem:
      type: object
      properties:
        endpoint:
          $ref: '#/components/schemas/Endpoint'
        metrics:
          type: object
          additionalProperties:
            type: array
            items:
              type: array
              items:
                type: number
      required:
      - endpoint
      - metrics
    Service:
      type: object
      properties:
        entityType:
          type: string
          description: Since, this is a Service, it will be of type `SERVICE`.
          enum:
          - APPLICATION
          - SERVICE
          - ENDPOINT
        id:
          type: string
          description: 'Unique ID of the Service. Eg: `3feb3dcd206c166ef2b41c707e0cd38d7cd325aa`.'
        label:
          type: string
          description: 'Name of the Service. Eg: `payment`.'
        snapshotIds:
          type: array
          description: A unique identifier the metrics are assigned to.
          items:
            type: string
            description: A unique identifier the metrics are assigned to.
          uniqueItems: true
        technologies:
          type: array
          description: 'List of technologies: `Eg:["springbootApplicationContainer"]`'
          items:
            type: string
            description: 'List of technologies: `Eg:["springbootApplicationContainer"]`'
          uniqueItems: true
        types:
          type: array
          description: 'Shows types of Endpoints a Service can consist of. It may be one or more. Eg: `HTTP` `OPENTELEMETRY` can be in 1 Service.'
          items:
            type: string
            description: 'Shows types of Endpoints a Service can consist of. It may be one or more. Eg: `HTTP` `OPENTELEMETRY` can be in 1 Service.'
            enum:
            - UNDEFINED
            - RPC
            - EVENT
            - GRAPHQL
            - BATCH
            - SHELL
            - HTTP
            - SDK
            - OPENTELEMETRY
            - INTERNAL
            - DATABASE
            - MESSAGING
            - PAGE
            - PAGE_RESOURCE
          uniqueItems: true
      required:
      - id
      - label
      - snapshotIds
      - technologies
      - types
    ServiceItem:
      type: object
      properties:
        metrics:
          type: object
          additionalProperties:
            type: array
            items:
              type: array
              items:
                type: number
        service:
          $ref: '#/components/schemas/Service'
      required:
      - metrics
      - service
    ServiceMetricResult:
      type: object
      properties:
        adjustedTimeframe:
          $ref: '#/components/schemas/AdjustedTimeframe'
        items:
          type: array
          items:
            $ref: '#/components/schemas/ServiceItem'
        page:
          type: integer
          format: int32
          description: Page Number
          minimum: 1
        pageSize:
          type: integer
          format: int32
          minimum: 1
        totalHits:
          type: integer
          format: int64
          minimum: 0
      required:
      - items
    GetServices:
      type: object
      properties:
        applicationBoundaryScope:
          type: string
          description: "Use when querying calls of an application:\n `INBOUND`: only inbound calls \n `ALL`: all the calls to that application (inbound + internal)"
          enum:
          - ALL
          - INBOUND
        applicationId:
          type: string
          description: 'An Instana generated unique identifier for an Application. If specified, the list of results will be filtered for the specified Application ID. Eg: `Av62RoIKQv-A3n6DbMQh9g`.

            One can see the application id from Instana UI by going to an Application Perspective page. In the URL, there will be `appId=Av62RoIKQv-A3n6DbMQh9g`.

            Alternatively, one can use `Get applications` API endpoint to get the application id in `id` parameter.

            '
          maxLength: 64
          minLength: 0
        contextScope:
          type: string
          description: "separate filtering and group by service id field\n - upstream is filtered on destination service and groups on source service\n - downstream is filtered on source service and groups on destination service\n - none is filtered on destination service and no grouping"
          enum:
          - NONE
          - UPSTREAM
          - DOWNSTREAM
        metrics:
          type: array
          description: 'A list of objects each of which defines a metric and the (statistical) aggregation -- MEAN, SUM, MAX, etc -- that should be used to summarize it for the defined time frame. Eg: `[{ ''metric'': ''latency'', ''aggregation'': ''MEAN''}]`. To know more about supported metrics and its aggregation, See `Get Metric catalog`.'
          items:
            $ref: '#/components/schemas/AppDataMetricConfiguration'
          maxItems: 5
          minItems: 1
        nameFilter:
          type: string
          description: 'filter by name with `contains` semantic. Eg: Let''s say there are 2 service names `ecomm-order` and `ecomm-deliver`, you can set `ecomm-` here to include the two Services.'
          maxLength: 256
          minLength: 0
        order:
          $ref: '#/components/schemas/Order'
        pagination:
          $ref: '#/components/schemas/Pagination'
        serviceId:
          type: string
          description: 'An Instana generated unique identifier for a Service. If specified, the list of results will be filtered for the specified Service ID. Eg: `3feb3dcd206c166ef2b41c707e0cd38d7cd325aa`.

            One can see the service id from Instana UI by going to a Service page. In the URL, there will be `serviceId=3feb3dcd206c166ef2b41c707e0cd38d7cd325aa`.

            Alternatively, one can use `Get services` API endpoint to get the service id in `id` parameter.

            '
          maxLength: 64
          minLength: 0
        technologies:
          type: array
          description: A list of technologies to be used for filtering data. For example, technologies could include AWS ECS, Cassandra, DB2, JVM, Kafka, etc. A full list of available technologies can be found in X.
          items:
            type: string
            description: A list of technologies to be used for filtering data. For example, technologies could include AWS ECS, Cassandra, DB2, JVM, Kafka, etc. A full list of available technologies can be found in X.
          maxItems: 20
          minItems: 0
          uniqueItems: true
        timeFrame:
          $ref: '#/components/schemas/TimeFrame'
      required:
      - metrics
    Order:
      type: object
      description: 'Specifies the ordering of the results.

        It contains fields that define the sorting criteria, the collation for sorting, and the direction in which the results should be ordered.

        '
      properties:
        by:
          type: string
          description: If the granularity is set to `1` you can use the metric name eg. `latency.p95` to order by that value.
        collation:
          type: string
          description: Language code used for sorting. Ignored for infrastructure queries.
        direction:
          type: string
          description: The order in which results will be sorted, either `ASC` for ascending or `DESC` for descending.
          enum:
          - ASC
          - DESC
      required:
      - by
      - direction
    TimeFrame:
      type: object
      description: Time range for which the data should be retrieved.
      properties:
        to:
          type: integer
          format: int64
          description: 'end of timeframe expressed as the Unix epoch time in milliseconds. Eg: `ISO 8601` standard time `2024-06-27T05:05:55.615Z` can be represented as `1719464755615` in Unix epoch time in milliseconds.'
        windowSize:
          type: integer
          format: int64
          description: windowSize in milliseconds
          maximum: 2678400000
          minimum: 0
    Application:
      type: object
      description: Returns a list of Application Perspectives.
      properties:
        boundaryScope:
          type: string
          description: Here, `ALL` Application Boundary Scope is considered.
        entityType:
          type: string
          description: Since, this is an Application Perspective, it will be of type `APPLICATION`.
          enum:
          - APPLICATION
          - SERVICE
          - ENDPOINT
        id:
          type: string
          description: 'Unique ID of the Application Perspective. Eg: `Av62RoIKQv-A3n6DbMQh9g`.'
        label:
          type: string
          description: 'Name of the Application Perspective. Eg: `app1`.'
      required:
      - boundaryScope
      - id
      - label
    GetApplicationMetrics:
      type: object
      properties:
        includeInternal:
          type: boolean
          writeOnly: true
        includeSynthetic:
          type: boolean
          writeOnly: true
        metrics:
          type: array
          items:
            $ref: '#/components/schemas/AppDataMetricConfiguration'
        tagFilterExpression:
          $ref: '#/components/schemas/TagFilterExpressionElement'
        timeFrame:
          $ref: '#/components/schemas/TimeFrame'
      required:
      - metrics
      - timeFrame
    EndpointMetricResult:
      type: object
      properties:
        adjustedTimeframe:
          $ref: '#/components/schemas/AdjustedTimeframe'
        items:
          type: array
          items:
            $ref: '#/components/schemas/EndpointItem'
        page:
          type: integer
          format: int32
          description: Page Number
          minimum: 1
        pageSize:
          type: integer
          format: int32
          minimum: 1
        totalHits:
          type: integer
          format: int64
          minimum: 0
      required:
      - items
    AppDataMetricConfiguration:
      type: object
      properties:
        aggregation:
          type: string
          description: 'Set aggregation that can be applied to a series of values. Eg: `MEAN`.'
          enum:
          - SUM
          - MEAN
          - MAX
          - MIN
          - P25
          - P50
          - P75
          - P90
          - P95
          - P98
          - P99
          - P99_9
          - P99_99
          - DISTINCT_COUNT
          - SUM_POSITIVE
          - PER_SECOND
          - INCREASE
        granularity:
          type: integer
          format: int32
          description: 'If the granularity is set you will get data points with the specified granularity in seconds. Default: `1000` milliseconds'
        metric:
          type: string
          description: 'Set a particular metric, eg: `latency`.'
        numeratorTagFilterExpression:
          $ref: '#/components/schemas/TagFilterExpressionElement'
      required:
      - aggregation
      - metric
    TagFilterExpressionElement:
      type: object
      description: Boolean expression of tag filters to define the scope of relevant calls.
      discriminator:
        mapping:
          EXPRESSION: '#/components/schemas/TagFilterExpression'
          TAG_FILTER: '#/components/schemas/TagFilter'
        propertyName: type
      properties:
        type:
          type: string
      required:
      - type
    Endpoint:
      type: object
      properties:
        entityType:
          type: string
          description: Since, this is a Endpoint, it will be of type `ENDPOINT`.
          enum:
          - APPLICATION
          - SERVICE
          - ENDPOINT
        id:
          type: string
          description: 'Unique ID of the Endpoint. Eg: `NCRq5oYnan5x-PkdTPQwLLUdu5M`.'
        isSynthetic:
          type: boolean
          writeOnly: true
        label:
          type: string
          description: 'Name of the Endpoint. Eg: `GET /api/fetch`.'
        serviceId:
          type: string
          description: The serviceId this endpoint belongs to.
        synthetic:
          type: boolean
        syntheticType:
          type: string
          enum:
          - NON_SYNTHETIC
          - SYNTHETIC
          - MIXED
        technologies:
          type: array
          description: 'List of technologies: `Eg:["springbootApplicationContainer"]`'
          items:
            type: string
            description: 'List of technologies: `Eg:["springbootApplicationContainer"]`'
          uniqueItems: true
        type:
          type: string
          description: The type of the Endpoint.
          enum:
          - UNDEFINED
          - RPC
          - EVENT
          - GRAPHQL
          - BATCH
          - SHELL
          - HTTP
          - SDK
          - OPENTELEMETRY
          - INTERNAL
          - DATABASE
          - MESSAGING
          - PAGE
          - PAGE_RESOURCE
      required:
      - id
      - label
      - serviceId
      - technologies
      - type
    ApplicationItem:
      type: object
      properties:
        application:
          $ref: '#/components/schemas/Application'
        metrics:
          type: object
          additionalProperties:
            type: array
            items:
              type: array
              items:
                type: number
      required:
      - application
      - metrics
    Pagination:
      type: object
      properties:
        page:
          type: integer
          format: int32
          description: Page number for a specific page in the results. For example, if you'd like to retrieve the 5th page out of 10 pages, the value would be 5.
          minimum: 1
        pageSize:
          type: integer
          format: int32
          description: 'Set the number of items you want to return with one query. Eg: if you want to retrieve 10 items, the value would be 10.'
          maximum: 200
          minimum: 1
    MetricAPIResult:
      type: object
      properties:
        adjustedTimeframe:
          $ref: '#/components/schemas/AdjustedTimeframe'
        metrics:
          type: object
          additionalProperties:
            type: array
            items:
              type: array
              items:
                type: number
      required:
      - metrics
    GetEndpoints:
      type: object
      properties:
        applicationBoundaryScope:
          type: string
          description: "Use when querying calls of an application:\n `INBOUND`: only inbound calls \n `ALL`: all the calls to that application (inbound + internal)"
          enum:
          - ALL
          - INBOUND
        applicationId:
          type: string
          description: 'An Instana generated unique identifier for an Application. If specified, the list of results will be filtered for the specified Application ID. Eg: `Av62RoIKQv-A3n6DbMQh9g`.

            One can see the application id from Instana UI by going to an Application Perspective page. In the URL, there will be `appId=Av62RoIKQv-A3n6DbMQh9g`.

            Alternatively, one can use `Get applications` API endpoint to get the application id in `id` parameter.

            '
          maxLength: 64
          minLength: 0
        endpointId:
          type: string
          description: 'An Instana generated unique identifier for an Endpoint. If specified, the list of results will be filtered for the specified Endpoint ID. Eg `NCRq5oYnan5x-PkdTPQwLLUdu5M`.

            One can see the endpoint id from Instana UI by going to an Endpoint page. In the URL, there will be `endpointId=NCRq5oYnan5x-PkdTPQwLLUdu5M`.

            Alternatively, one can use `Get endpoints` API endpoint to get the endpoint id in `id` parameter.

            '
          maxLength: 64
          minLength: 0
        endpointTypes:
          type: array
          description: A list of endpoint types, each of which is a string. An endpoint can specified for a database, an SDK, etc.
          items:
            type: string
            description: A list of endpoint types, each of which is a string. An endpoint can specified for a database, an SDK, etc.
            enum:
            - UNDEFINED
            - RPC
            - EVENT
            - GRAPHQL
            - BATCH
            - SHELL
            - HTTP
            - SDK
            - OPENTELEMETRY
            - INTERNAL
            - DATABASE
            - MESSAGING
            - PAGE
            - PAGE_RESOURCE
          maxItems: 8
          minItems: 0
          uniqueItems: true
        excludeSynthetic:
          type: boolean
          description: A variable used to specify whether synthetic endpoints should be excluded. If set to 'true', synthetic endpoints will be excluded from the result.
        metrics:
          type: array
          description: 'A list of objects each of which defines a metric and the (statistical) aggregation -- MEAN, SUM, MAX, etc -- that should be used to summarize it for the defined time frame. Eg: `[{ ''metric'': ''latency'', ''aggregation'': ''MEAN''}]`. To know more about supported metrics and its aggregation, See `Get Metric catalog`.'
          items:
            $ref: '#/components/schemas/AppDataMetricConfiguration'
          maxItems: 5
          minItems: 1
        nameFilter:
          type: string
          description: 'filter by endpoint name with `contains` semantic. Eg: Let''s say there are 2 Endpoint names `GET /api/fetch` and `GET /api/update`, you can set `GET /api/` here to include the two Endpoints.'
          maxLength: 256
          minLength: 0
        order:
          $ref: '#/components/schemas/Order'
        pagination:
          $ref: '#/components/schemas/Pagination'
        serviceId:
          type: string
          description: 'An Instana generated unique identifier for a Service. If specified, the list of results will be filtered for the specified Service ID. Eg: `3feb3dcd206c166ef2b41c707e0cd38d7cd325aa`.

            One can see the service id from Instana UI by going to a Service page. In the URL, there will be `serviceId=3feb3dcd206c166ef2b41c707e0cd38d7cd325aa`.

            Alternatively, one can use `Get services` API endpoint to get the service id in `id` parameter.

            '
          maxLength: 64
          minLength: 0
        timeFrame:
          $ref: '#/components/schemas/TimeFrame'
      required:
      - metrics
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: authorization
      type: apiKey
      description: "## Example\n\n```bash\ncurl --request GET \\\n  --url https://test-instana.instana.io/api/application-monitoring/catalog/metrics \\\n  --header 'authorization: apiToken xxxxxxxxxxxxxxxx'\n```\n"
x-tagGroups:
- name: Websites & Mobile Apps
  tags:
  - Website Metrics
  - Website Catalog
  - Website Analyze
  - Website Configuration
  - Mobile App Metrics
  - Mobile App Catalog
  - Mobile App Analyze
  - Mobile App Configuration
  - End User Monitoring
- name: Applications
  tags:
  - Application Metrics
  - Application Resources
  - Application Catalog
  - Application Analyze
  - Application Settings
  - Application Topology
  - Application Alert Configuration
  - Global Application Alert Configuration
- name: Infrastructure
  tags:
  - Infrastructure Analyze
  - Infrastructure Metrics
  - Infrastructure Resources
  - Infrastructure Catalog
  - Infrastructure Topology
- name: Logging
  tags:
  - Logging Analyze
- name: Synthetic Monitoring
  tags:
  - Synthetic Catalog
  - Synthetic Metrics
  - Synthetic Settings
  - Synthetic Test Playback Results
  - Synthetic Alert Configuration
- name: Logs
  tags:
  - Log Alert Configuration
- name: Events
  tags:
  - Events
  - Event Settings
- name: Automation
  tags:
  - Action Catalog
  - Action History
  - Policies
- name: Service Levels
  tags:
  - SLI Settings
  - SLI Report
  - Apdex Settings
  - Apdex Report
  - Service Levels Objective(SLO) Configurations
  - Service Levels Objective(SLO) Report
  - Service Levels Alert Configuration
  - SLO Correction Configurations
  - SLO Correction Windows
- name: AI Management
  tags:
  - AI Management
- name: Settings
  tags:
  - Custom Dashboards
  - User
  - Groups
  - Teams
  - Roles
  - Audit Log
  - API Token
  - Maintenance Configuration
  - Synthetic Calls
  - Session Settings
  - Automation Settings
  - Authentication
- name: Open Beta Features
  tags:
  - Infrastructure Analyze
- name: Closed Beta Features
  tags:
  - Infrastructure Alert Configuration
- name: Instana
  tags:
  - Releases
  - Host Agent
  - Health
  - Usage
