openapi: 3.2.0
info:
  contact:
    email: support@instana.com
    name: © Instana
    url: http://instana.com
  termsOfService: https://www.instana.com/terms-of-use/
  title: Instana REST API documentation Apdex Settings API
  version: 1.307.1417
  x-ibm-ahub-try: true
  x-logo:
    altText: instana logo
    backgroundColor: '#FAFBFC'
    url: header-logo.svg
  description: Searching for answers and best pratices?
servers:
- description: Instana Backend
  url: https://{unit}-{tenant}.instana.io
  variables:
    tenant:
      default: tenant
      description: Customer tenant unit
    unit:
      default: unit
      description: Customer tenant name
- description: Instana Self-Hosted Backend
  url: https://{domain}
  variables:
    domain:
      default: example.com
      description: Customer Self-Hosted domain
tags:
- name: Apdex Settings
paths:
  /api/settings/apdex:
    get:
      description: API to Get All Apdex Configurations.
      operationId: getAllApdexConfigurations
      responses:
        '200':
          content:
            application/json:
              example:
              - id: _PvpxqTfSyi27O_LCxMd0A
                createdAt: 1653917798682
                apdexName: '{string}'
                apdexEntity:
                  apdexType: website
                  entityId: '{object}'
                  threshold: 70
                  tagFilterExpression:
                    type: EXPRESSION
                    logicalOperator: AND
                    elements: []
                  beaconType: httpRequest
              - id: K6thQVyzQqWc38yspc0QWw
                createdAt: 1693828514423
                apdexName: '{string}'
                apdexEntity:
                  apdexType: application
                  entityId: '{object}'
                  threshold: 12
                  tagFilterExpression:
                    type: EXPRESSION
                    logicalOperator: AND
                    elements: []
                  boundaryScope: ALL
                  includeInternal: false
                  includeSynthetic: false
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApdexConfiguration'
          description: OK
      security:
      - ApiKeyAuth:
        - Default
      summary: Get All Apdex Configurations
      tags:
      - Apdex Settings
      x-ibm-ahub-byok: true
    post:
      operationId: createApdexConfiguration
      requestBody:
        content:
          application/json:
            example:
            - apdexName: Apdex Configuration One
              apdexEntity:
                apdexType: website
                entityId: XIZGGVT1TX2O-0OFeT2Yig
                threshold: 400
                tagFilterExpression:
                  type: EXPRESSION
                  logicalOperator: AND
                  elements: []
                beaconType: httpRequest
            schema:
              $ref: '#/components/schemas/ApdexConfigurationInput'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApdexConfiguration'
          description: OK
      security:
      - ApiKeyAuth:
        - canConfigureApdex
      summary: Create Apdex Configuration
      tags:
      - Apdex Settings
      x-ibm-ahub-byok: true
  /api/settings/apdex/{entityType}/{entityId}:
    get:
      description: API to Get All Apdex Configurations for specified entity type and entity id.
      operationId: getApdexConfigurationsForEntityTypeAndId
      parameters:
      - description: Type of the Apdex Configuration, it could be APPLICATION or WEBSITE
        example: APPLICATION
        in: path
        name: entityType
        required: true
        schema:
          type: string
          enum:
          - APPLICATION
          - WEBSITE
      - description: Application or Website ID
        example: XIZGGVT1TX2O-0OFeT2Yig
        in: path
        name: entityId
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              example:
              - id: u2MBXtasQoy3reni5-QZgg
                createdAt: 1657743333352
                apdexName: Apdex Configuration One
                apdexEntity:
                  apdexType: website
                  entityId: XIZGGVT1TX2O-0OFeT2Yig
                  threshold: 400
                  tagFilterExpression:
                    type: EXPRESSION
                    logicalOperator: AND
                    elements: []
                  beaconType: httpRequest
              - id: ShIqRJgpTT69HZHbfQKRGg
                createdAt: 1693482558276
                apdexName: Apdex Configuration Two
                apdexEntity:
                  apdexType: website
                  entityId: XIZGGVT1TX2O-0OFeT2Yig
                  threshold: 90
                  tagFilterExpression:
                    type: EXPRESSION
                    logicalOperator: AND
                    elements: []
                  beaconType: httpRequest
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApdexConfiguration'
          description: OK
        '400':
          content:
            application/json:
              example: '{"code":400,"message":"path param entityType must be one of [APPLICATION, WEBSITE]"}'
              schema:
                type: string
          description: Bad Request
      security:
      - ApiKeyAuth:
        - Default
      summary: Get all Apdex configurations for entity type and entity id
      tags:
      - Apdex Settings
      x-ibm-ahub-byok: true
  /api/settings/apdex/{id}:
    delete:
      operationId: deleteApdexConfiguration
      parameters:
      - description: Apdex Configuration ID
        example: NCAoNKqySWSK1U5GkmyZgQ
        in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '204':
          description: Apdex Configuration Deleted Successfully
      security:
      - ApiKeyAuth:
        - canConfigureApdex
      summary: Delete Apdex Configuration
      tags:
      - Apdex Settings
      x-ibm-ahub-byok: true
    get:
      description: API to Get Apdex Configuration for specified ID.
      operationId: getApdexConfiguration
      parameters:
      - description: Apdex Configuration ID
        example: NCAoNKqySWSK1U5GkmyZgQ
        in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              example:
                id: NCAoNKqySWSK1U5GkmyZgQ
                createdAt: 1666112381045
                apdexName: '{string}'
                apdexEntity:
                  apdexType: website
                  entityId: XIZGGVT1TX2O-0OFeT2Yig
                  threshold: 100
                  tagFilterExpression:
                    type: EXPRESSION
                    logicalOperator: AND
                    elements: []
                  beaconType: httpRequest
              schema:
                $ref: '#/components/schemas/ApdexConfiguration'
          description: OK
        '404':
          content:
            application/json:
              example: '{"errors":["Apdex Configuration not found"]}'
              schema:
                type: string
          description: Apdex Configuration not found
      security:
      - ApiKeyAuth:
        - Default
      summary: Get Apdex Configuration
      tags:
      - Apdex Settings
      x-ibm-ahub-byok: true
components:
  schemas:
    ApdexConfiguration:
      type: object
      properties:
        apdexEntity:
          $ref: '#/components/schemas/ApdexEntity'
        apdexName:
          type: string
          description: Name of the Apdex Configuration
          maxLength: 256
          minLength: 0
        createdAt:
          type: integer
          format: int64
          description: Created Date of Apdex Configuration
        id:
          type: string
          description: Apdex Configuration ID
          maxLength: 64
          minLength: 0
      required:
      - apdexEntity
      - apdexName
      - id
    ApdexConfigurationInput:
      type: object
      properties:
        apdexEntity:
          $ref: '#/components/schemas/ApdexEntity'
        apdexName:
          type: string
          description: Name of the Apdex Configuration
          maxLength: 256
          minLength: 0
      required:
      - apdexEntity
      - apdexName
    ApdexEntity:
      type: object
      description: Entity which holds the information of Apdex Configuration
      discriminator:
        mapping:
          application: '#/components/schemas/ApplicationApdexEntity'
          website: '#/components/schemas/WebsiteApdexEntity'
        propertyName: apdexType
      properties:
        apdexType:
          type: string
        entityId:
          type: string
        tagFilterExpression:
          $ref: '#/components/schemas/TagFilterExpressionElement'
        threshold:
          type: integer
          format: int32
          minimum: 1
      required:
      - apdexType
      - entityId
      - tagFilterExpression
    TagFilterExpressionElement:
      type: object
      description: Boolean expression of tag filters to define the scope of relevant calls.
      discriminator:
        mapping:
          EXPRESSION: '#/components/schemas/TagFilterExpression'
          TAG_FILTER: '#/components/schemas/TagFilter'
        propertyName: type
      properties:
        type:
          type: string
      required:
      - type
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: authorization
      type: apiKey
      description: "## Example\n\n```bash\ncurl --request GET \\\n  --url https://test-instana.instana.io/api/application-monitoring/catalog/metrics \\\n  --header 'authorization: apiToken xxxxxxxxxxxxxxxx'\n```\n"
x-tagGroups:
- name: Websites & Mobile Apps
  tags:
  - Website Metrics
  - Website Catalog
  - Website Analyze
  - Website Configuration
  - Mobile App Metrics
  - Mobile App Catalog
  - Mobile App Analyze
  - Mobile App Configuration
  - End User Monitoring
- name: Applications
  tags:
  - Application Metrics
  - Application Resources
  - Application Catalog
  - Application Analyze
  - Application Settings
  - Application Topology
  - Application Alert Configuration
  - Global Application Alert Configuration
- name: Infrastructure
  tags:
  - Infrastructure Analyze
  - Infrastructure Metrics
  - Infrastructure Resources
  - Infrastructure Catalog
  - Infrastructure Topology
- name: Logging
  tags:
  - Logging Analyze
- name: Synthetic Monitoring
  tags:
  - Synthetic Catalog
  - Synthetic Metrics
  - Synthetic Settings
  - Synthetic Test Playback Results
  - Synthetic Alert Configuration
- name: Logs
  tags:
  - Log Alert Configuration
- name: Events
  tags:
  - Events
  - Event Settings
- name: Automation
  tags:
  - Action Catalog
  - Action History
  - Policies
- name: Service Levels
  tags:
  - SLI Settings
  - SLI Report
  - Apdex Settings
  - Apdex Report
  - Service Levels Objective(SLO) Configurations
  - Service Levels Objective(SLO) Report
  - Service Levels Alert Configuration
  - SLO Correction Configurations
  - SLO Correction Windows
- name: AI Management
  tags:
  - AI Management
- name: Settings
  tags:
  - Custom Dashboards
  - User
  - Groups
  - Teams
  - Roles
  - Audit Log
  - API Token
  - Maintenance Configuration
  - Synthetic Calls
  - Session Settings
  - Automation Settings
  - Authentication
- name: Open Beta Features
  tags:
  - Infrastructure Analyze
- name: Closed Beta Features
  tags:
  - Infrastructure Alert Configuration
- name: Instana
  tags:
  - Releases
  - Host Agent
  - Health
  - Usage
