openapi: 3.2.0
info:
  contact:
    email: support@instana.com
    name: © Instana
    url: http://instana.com
  termsOfService: https://www.instana.com/terms-of-use/
  title: Instana REST API documentation Maintenance Configuration API
  version: 1.307.1417
  x-ibm-ahub-try: true
  x-logo:
    altText: instana logo
    backgroundColor: '#FAFBFC'
    url: header-logo.svg
  description: Searching for answers and best pratices?
servers:
- description: Instana Backend
  url: https://{unit}-{tenant}.instana.io
  variables:
    tenant:
      default: tenant
      description: Customer tenant unit
    unit:
      default: unit
      description: Customer tenant name
- description: Instana Self-Hosted Backend
  url: https://{domain}
  variables:
    domain:
      default: example.com
      description: Customer Self-Hosted domain
tags:
- name: Maintenance Configuration
  description: '### Maintenance Windows

    Maintenance windows allow you to mute alerts.'
paths:
  /api/settings/maintenance:
    get:
      deprecated: true
      description: For more information on Maintenance Configurations please access the https://developer.ibm.com/apis/catalog/instana--instana-rest-api/Settings#maintenance-configurations.
      operationId: getMaintenanceConfigs
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ValidatedMaintenanceConfigWithStatus'
          description: OK
      security:
      - ApiKeyAuth:
        - CanConfigureMaintenanceWindows
      summary: All maintenance configurations
      tags:
      - Maintenance Configuration
      x-ibm-ahub-byok: true
  /api/settings/maintenance/{id}:
    delete:
      deprecated: true
      description: For more information on Maintenance Configurations please access the https://developer.ibm.com/apis/catalog/instana--instana-rest-api/Settings#maintenance-configurations.
      operationId: deleteMaintenanceConfig
      parameters:
      - description: ID of the Maintenance Window Configuration to delete.
        example: MPhKWoXRp0PBelqk
        in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        default:
          content:
            application/json: {}
          description: default response
      security:
      - ApiKeyAuth:
        - CanConfigureMaintenanceWindows
      summary: Delete maintenance configuration
      tags:
      - Maintenance Configuration
      x-ibm-ahub-byok: true
    get:
      deprecated: true
      description: For more information on Maintenance Configurations please access the https://developer.ibm.com/apis/catalog/instana--instana-rest-api/Settings#maintenance-configurations.
      operationId: getMaintenanceConfig
      parameters:
      - description: ID of the Maintenance Window Configuration to get.
        example: MPhKWoXRp0PBelqk
        in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MaintenanceConfigWithLastUpdated'
          description: OK
      security:
      - ApiKeyAuth:
        - CanConfigureMaintenanceWindows
      summary: Maintenance configuration
      tags:
      - Maintenance Configuration
      x-ibm-ahub-byok: true
    put:
      deprecated: true
      description: For more information on Maintenance Configurations please access the https://developer.ibm.com/apis/catalog/instana--instana-rest-api/Settings#maintenance-configurations.
      operationId: putMaintenanceConfig
      parameters:
      - description: ID of the Maintenance Window Configuration to update.
        example: MPhKWoXRp0PBelqk
        in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MaintenanceConfig'
        required: true
      responses:
        '200':
          description: Maintenance config has been created or updated, and successfully scheduled immediately if needed
        '202':
          description: Maintenance config has been created or updated, but could not to be scheduled immediately. It will therefore be scheduled during the next auto-refresh with a delay of up to 4 minutes.
        '400':
          description: Invalid JSON or mismatching IDs have been provided
      security:
      - ApiKeyAuth:
        - CanConfigureMaintenanceWindows
      summary: Create or update maintenance configuration
      tags:
      - Maintenance Configuration
      x-ibm-ahub-byok: true
  /api/settings/v2/maintenance:
    get:
      operationId: getMaintenanceConfigsV2
      responses:
        '200':
          content:
            application/json:
              example:
              - id: maintenanceConfigId
                name: maintenanceConfig
                query: entity.application.id:"anApplicationId"
                scheduling:
                  start: 1680703219486
                  duration:
                    amount: 2
                    unit: HOURS
                  rrule: FREQ=DAILY;INTERVAL=1;COUNT=1
                  timezoneId: UTC
                  type: RECURRENT
                paused: false
                lastUpdated: 1680703219678
                state: EXPIRED
                validVersion: 1
                occurrence:
                  start: 1680703219000
                  end: 1680710419000
                invalid: false
                applicationNames:
                - anApplicationName
              - id: anotherMaintenanceConfigId
                name: anotherMaintenanceConfig
                query: entity.type:ibmz.db2
                scheduling:
                  start: 1680703219486
                  duration:
                    amount: 2
                    unit: HOURS
                  rrule: FREQ=DAILY;INTERVAL=1;COUNT=1
                  timezoneId: UTC
                  type: RECURRENT
                paused: false
                lastUpdated: 1680703219678
                state: EXPIRED
                validVersion: 1
                occurrence:
                  start: 1680703219000
                  end: 1680710419000
                invalid: false
                applicationNames: []
              - id: '1698949644924'
                name: sampleMaintenanceConfig
                query: ''
                scheduling:
                  start: 1698949644924
                  duration:
                    amount: 2
                    unit: HOURS
                  rrule: FREQ=WEEKLY;INTERVAL=2;BYDAY=SA;COUNT=10
                  timezoneId: America/New_York
                  type: RECURRENT
                paused: false
                validVersion: 1
                tagFilterExpression:
                  type: EXPRESSION
                  logicalOperator: OR
                  elements:
                  - type: TAG_FILTER
                    name: synthetic.locationLabelAggregated
                    stringValue: us-east
                    numberValue: null
                    booleanValue: null
                    key: null
                    value: us-east
                    operator: EQUALS
                    entity: NOT_APPLICABLE
                  - type: TAG_FILTER
                    name: synthetic.syntheticType
                    stringValue: HTTPScript
                    numberValue: null
                    booleanValue: null
                    key: null
                    value: HTTPScript
                    operator: EQUALS
                    entity: NOT_APPLICABLE
                tagFilterExpressionEnabled: true
                retriggerOpenAlertsEnabled: true
                lastUpdated: 1698949645163
                state: SCHEDULED
                occurrence:
                  start: 1699122444000
                  end: 1699129644000
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ValidatedMaintenanceConfigV2WithStateAndOccurrence'
          description: OK
      security:
      - ApiKeyAuth:
        - CanConfigureMaintenanceWindows
      summary: All maintenance configurations
      tags:
      - Maintenance Configuration
      x-ibm-ahub-byok: true
      description: This endpoint retrieves all available maintenance configurations.
  /api/settings/v2/maintenance/{id}:
    delete:
      operationId: deleteMaintenanceConfigV2
      parameters:
      - description: Id of the Maintenance Window configuration to delete.
        example: 8924aa6b
        in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        default:
          content:
            application/json: {}
          description: default response
      security:
      - ApiKeyAuth:
        - CanConfigureMaintenanceWindows
      summary: Delete maintenance configuration
      tags:
      - Maintenance Configuration
      x-ibm-ahub-byok: true
      description: 'This endpoint deletes a maintenance configuration given its ID.


        ### Path Parameters:


        - **id:** The ID of the maintenance config to delete.'
    get:
      operationId: getMaintenanceConfigV2
      parameters:
      - description: Id of the Maintenance Window Configuration to get.
        example: 8924aa6b
        in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              example:
                id: maintenanceConfigId
                name: maintenanceConfig
                query: ''
                scheduling:
                  start: 1683864000000
                  duration:
                    amount: 24
                    unit: HOURS
                  type: ONE_TIME
                paused: false
                validVersion: 1
                lastUpdated: 1683901553115
                state: EXPIRED
                occurrence:
                  start: 1683864000000
                  end: 1683950400000
              schema:
                $ref: '#/components/schemas/MaintenanceConfigV2WithStateAndOccurrence'
          description: OK
      security:
      - ApiKeyAuth:
        - CanConfigureMaintenanceWindows
      summary: Get maintenance configuration
      tags:
      - Maintenance Configuration
      x-ibm-ahub-byok: true
      description: 'This endpoint retrieves a maintenance configuration given its ID.


        ### Path Parameters:


        - **id:** The ID of the maintenance config to fetch.'
    put:
      operationId: putMaintenanceConfigV2
      parameters:
      - description: Id of the Maintenance Window configuration to update.
        example: 8924aa6b
        in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MaintenanceConfigV2'
            examples:
              payload:
                value:
                  id: maintenanceConfigID
                  name: sampleMaintenanceConfig
                  query: ''
                  scheduling:
                    start: 1683827571245
                    duration:
                      amount: 2
                      unit: HOURS
                    type: RECURRENT
                    rrule: FREQ=WEEKLY;INTERVAL=2;BYDAY=SA;COUNT=10
                    timezoneId: America/New_York
                  tagFilterExpressionEnabled: true
                  tagFilterExpression:
                    type: EXPRESSION
                    logicalOperator: OR
                    elements:
                    - type: TAG_FILTER
                      name: synthetic.locationLabelAggregated
                      stringValue: us-east
                      numberValue: null
                      booleanValue: null
                      key: null
                      value: us-east
                      operator: EQUALS
                      entity: NOT_APPLICABLE
                    - type: TAG_FILTER
                      name: synthetic.syntheticType
                      stringValue: HTTPScript
                      numberValue: null
                      booleanValue: null
                      key: null
                      value: HTTPScript
                      operator: EQUALS
                      entity: NOT_APPLICABLE
        required: true
      responses:
        '200':
          content:
            application/json:
              example:
                id: maintenanceConfigId
                name: maintenanceConfig
                query: ''
                scheduling:
                  start: 1698938631036
                  duration:
                    amount: 2
                    unit: HOURS
                  type: ONE_TIME
                paused: false
                validVersion: 1
                tagFilterExpression:
                  type: EXPRESSION
                  logicalOperator: OR
                  elements:
                  - type: TAG_FILTER
                    name: synthetic.locationLabelAggregated
                    stringValue: us-east
                    numberValue: null
                    booleanValue: null
                    key: null
                    value: us-east
                    operator: EQUALS
                    entity: NOT_APPLICABLE
                  - type: TAG_FILTER
                    name: synthetic.syntheticType
                    stringValue: HTTPScript
                    numberValue: null
                    booleanValue: null
                    key: null
                    value: HTTPScript
                    operator: EQUALS
                    entity: NOT_APPLICABLE
                tagFilterExpressionEnabled: true
                retriggerOpenAlertsEnabled: true
                lastUpdated: 1698938631408
                state: ACTIVE
                occurrence:
                  start: 1698938631036
                  end: 1698945831036
          description: Maintenance config has been created or updated, and successfully scheduled immediately if needed
        '202':
          description: Maintenance config has been created or updated, but could not to be scheduled immediately. It will therefore be scheduled during the next auto-refresh with a delay of up to 4 minutes.
        '400':
          description: The provided maintenance configuration is invalid.
        '422':
          description: The provided maintenance configuration is incomplete or cannot be processed.
      security:
      - ApiKeyAuth:
        - CanConfigureMaintenanceWindows
      summary: Create or update maintenance configuration
      tags:
      - Maintenance Configuration
      x-ibm-ahub-byok: true
      description: 'This endpoint creates or updates a maintenance configuration given its ID.


        ### Path Parameters:


        - **id:** The ID of the maintenance config to create or update.


        ### Maintenance Configuration Input

        This is a description for the fields in the request body:


        **id**: maintenance configuration unique id

        **name**: maintenance configuration name

        **query**: dynamic focus query used to filter alert notifications that will be muted

        **scheduling**: defines when the maintenance configuration will be scheduled

        - **start**: time in milliseconds from epoch

        - **duration**: duration of each maintenance window occurrence in the maintenance configuration

        - **amount**: the amount of time

        - **unit**: the unit of time

        - **type**: `ONE_TIME` or `RECURRENT`

        - **rrule**: for `RECURRENT` mainteance configurations, the RRULE standard from the iCalendar Spec

        - **paused**: indicates whether maintenance configuration is paused or not


        **tagFilterExpressionEnabled (OPTIONAL) (Closed Beta)**: indicates whether tagFilterExpression is used to filter alert notifications

        **tagFilterExpression (OPTIONAL) (Closed Beta)**: tag filter expression used to filter alert notifications that will be muted (this field needs to be provided if **tagFilterExpressionEnabled** is set to true)


        ### **Scope**

        There are four supported scopes; application perspective, dynamic focus query, synthetic tests, all entities. Below is the configuration corresponding to each scope:


        **1. Application Perspective**

        dfq: a valid dynamic focus query

        tfeEnabled: (optional)

        tfe: (optional)


        **2. Dynamic Focus Query**

        dfq: a valid dynamic focus query

        tfeEnabled: (optional)

        tfe: (optional)


        **3. Synthetic Tests**

        dfq: ""

        tfeEnabled: true

        tfe: a valid tag filter expression


        **4. All Entities**

        dfq: ""

        tfeEnabled: false

        tfe: null


        ### **RRULE Support**

        You can use the RRULE tool for generating RRULEs.


        The following RRULE tokens are supported: `FREQ`, `UNTIL`, `COUNT`, `INTERVAL`, `BYDAY`, `BYMONTHDAY`, `BYMONTH`.


        **Additional Constraints:**


        1. For `MONTHLY` and `YEARLY`, you can only specify one value for `BYDAY` and `BYMONTHDAY`.

        2. The maximum `INTERVAL` allowed is as follows:

        - DAILY is 365

        - WEEKLY is 52

        - MONTHLY is 12

        - YEARLY is 1

        3. If an `UNTIL` date is specified, the value needs to be in UTC.


        ### **Tag Filter Expression Support**

        We support the following tag filters:

        - synthetic.syntheticType

        - synthetic.testName

        - synthetic.locationLabelAggregated

        - synthetic.tags'
  /api/settings/v2/maintenance/{id}/pause:
    put:
      operationId: pauseRecurrentMaintenanceConfiguration
      parameters:
      - description: Id of the Maintenance Window configuration to pause.
        example: 8924aa6b
        in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              example:
                id: maintenanceConfigId
                name: maintenanceConfig
                query: entity.application.id:"anApplicationId"
                scheduling:
                  start: 1684251745262
                  duration:
                    amount: 2
                    unit: HOURS
                  type: ONE_TIME
                paused: true
                validVersion: 1
                lastUpdated: 1684251750475
                state: PAUSED
                occurrence:
                  start: 1684251745262
                  end: 1684258945262
              schema:
                $ref: '#/components/schemas/MaintenanceConfigV2WithStateAndOccurrence'
          description: OK
      security:
      - ApiKeyAuth:
        - CanConfigureMaintenanceWindows
      summary: Pause maintenance configuration
      tags:
      - Maintenance Configuration
      x-ibm-ahub-byok: true
      description: 'This endpoint pauses a maintenance configuration given its ID.


        When you pause a maintenance configuration, you will start receiving alerts again for the scope defined in the maintenance configuration.

        ### Path Parameters:


        - **id:** The ID of the maintenance config to pause.'
  /api/settings/v2/maintenance/{id}/resume:
    put:
      operationId: resumeRecurrentMaintenanceConfiguration
      parameters:
      - description: Id of the Maintenance Window configuration to resume.
        example: 8924aa6b
        in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              example:
                id: maintenanceConfigId
                name: maintenanceConfig
                query: entity.application.id:"anApplicationId"
                scheduling:
                  start: 1684251745262
                  duration:
                    amount: 2
                    unit: HOURS
                  type: ONE_TIME
                paused: false
                validVersion: 1
                lastUpdated: 1684251933433
                state: ACTIVE
                occurrence:
                  start: 1684251745262
                  end: 1684258945262
              schema:
                $ref: '#/components/schemas/MaintenanceConfigV2WithStateAndOccurrence'
          description: OK
      security:
      - ApiKeyAuth:
        - CanConfigureMaintenanceWindows
      summary: Resume maintenance configuration
      tags:
      - Maintenance Configuration
      x-ibm-ahub-byok: true
      description: 'This endpoint resumes a maintenance configuration given its ID.


        If the maintenance configuration becomes active when you resume the maintenance configuration, you will not receive alerts for the scope defined in the maintenance configuration.

        ### Path Parameters:


        - **id:** The ID of the maintenance config to resume.'
components:
  schemas:
    MaintenanceConfig:
      type: object
      properties:
        id:
          type: string
          description: ID of the Maintenance Window Configuration.
          maxLength: 64
          minLength: 0
        name:
          type: string
          description: Name of the Maintenance Window Configuration.
          maxLength: 256
          minLength: 0
        query:
          type: string
          description: Dynamic Focus Query that determines the scope of the Maintenance Window configuration.
          maxLength: 2048
          minLength: 0
        windows:
          type: array
          description: A set of time periods when the Maintenance Window Configuration is active.
          items:
            $ref: '#/components/schemas/MaintenanceWindow'
          maxItems: 1
          minItems: 0
          uniqueItems: true
      required:
      - id
      - name
      - query
    TagFilterExpressionElement:
      type: object
      description: Boolean expression of tag filters to define the scope of relevant calls.
      discriminator:
        mapping:
          EXPRESSION: '#/components/schemas/TagFilterExpression'
          TAG_FILTER: '#/components/schemas/TagFilter'
        propertyName: type
      properties:
        type:
          type: string
      required:
      - type
    Occurrence:
      type: object
      description: Time window of the Maintence Window configuration occurrences.
      properties:
        end:
          type: integer
          format: int64
          minimum: 1
        start:
          type: integer
          format: int64
          minimum: 0
    ValidatedMaintenanceConfigV2WithStateAndOccurrence:
      type: object
      properties:
        applicationNames:
          type: array
          description: Name set of the Application Perspectives within the scope of the Maintenance Window
          items:
            type: string
            description: Name set of the Application Perspectives within the scope of the Maintenance Window
          uniqueItems: true
        id:
          type: string
          description: ID of the Maintenance Window configuration.
          maxLength: 64
          minLength: 0
        invalid:
          type: boolean
          description: Boolean flag that tells if the Dynamic Focus Query(DFQ) is invalid.
        lastUpdated:
          type: integer
          format: int64
          minimum: 1
        name:
          type: string
          description: Name of the Maintenance Window configuration.
          maxLength: 256
          minLength: 0
        occurrence:
          $ref: '#/components/schemas/Occurrence'
        paused:
          type: boolean
          description: Boolean flag to determine if the Maintenance Window configuration is paused or still live.
        query:
          type: string
          description: Dynamic Focus Query that determines the scope of the Maintenance Window configuration.
          maxLength: 2048
          minLength: 0
        retriggerOpenAlertsEnabled:
          type: boolean
          description: Boolean flag to determine if we should retrigger open alerts to be sent out for any events that opened during this maintenance window, and continues to remain open after the window expires
        scheduling:
          $ref: '#/components/schemas/MaintenanceConfigScheduling'
        state:
          type: string
          description: 'State of the Maintenance Window, it can be: UNSCHEDULED, SCHEDULED, ACTIVE, PAUSED, EXPIRED.'
          enum:
          - UNSCHEDULED
          - SCHEDULED
          - ACTIVE
          - PAUSED
          - EXPIRED
        tagFilterExpression:
          $ref: '#/components/schemas/TagFilterExpressionElement'
        tagFilterExpressionEnabled:
          type: boolean
          description: Boolean flag to determine if the tagFilterExpression is enabled.
      required:
      - id
      - name
      - occurrence
      - query
      - scheduling
    ValidatedMaintenanceConfigWithStatus:
      type: object
      properties:
        id:
          type: string
          description: ID of the Maintenance Window Configuration.
          maxLength: 64
          minLength: 0
        invalid:
          type: boolean
          description: Boolean flag that tells if the Dynamic Focus Query(DFQ) is invalid.
        lastUpdated:
          type: integer
          format: int64
          minimum: 1
        name:
          type: string
          description: Name of the Maintenance Window Configuration.
          maxLength: 256
          minLength: 0
        query:
          type: string
          description: Dynamic Focus Query that determines the scope of the Maintenance Window configuration.
          maxLength: 2048
          minLength: 0
        status:
          type: string
          description: 'Status of the Maintenance Window Configuration. It can be one of: UNSCHEDULED, SCHEDULED, ACTIVE, FINISHED, PAUSED.'
          enum:
          - UNSCHEDULED
          - SCHEDULED
          - ACTIVE
          - FINISHED
          - PAUSED
        windows:
          type: array
          description: A set of time periods when the Maintenance Window Configuration is active.
          items:
            $ref: '#/components/schemas/MaintenanceWindow'
          maxItems: 1
          minItems: 0
          uniqueItems: true
      required:
      - id
      - name
      - query
      - status
    MaintenanceConfigV2:
      type: object
      properties:
        id:
          type: string
          description: ID of the Maintenance Window configuration.
          maxLength: 64
          minLength: 0
        name:
          type: string
          description: Name of the Maintenance Window configuration.
          maxLength: 256
          minLength: 0
        paused:
          type: boolean
          description: Boolean flag to determine if the Maintenance Window configuration is paused or still live.
        query:
          type: string
          description: Dynamic Focus Query that determines the scope of the Maintenance Window configuration.
          maxLength: 2048
          minLength: 0
        retriggerOpenAlertsEnabled:
          type: boolean
          description: Boolean flag to determine if we should retrigger open alerts to be sent out for any events that opened during this maintenance window, and continues to remain open after the window expires
        scheduling:
          $ref: '#/components/schemas/MaintenanceConfigScheduling'
        tagFilterExpression:
          $ref: '#/components/schemas/TagFilterExpressionElement'
        tagFilterExpressionEnabled:
          type: boolean
          description: Boolean flag to determine if the tagFilterExpression is enabled.
      required:
      - id
      - name
      - query
      - scheduling
    MaintenanceConfigV2WithStateAndOccurrence:
      type: object
      properties:
        id:
          type: string
          description: ID of the Maintenance Window configuration.
          maxLength: 64
          minLength: 0
        lastUpdated:
          type: integer
          format: int64
          minimum: 1
        name:
          type: string
          description: Name of the Maintenance Window configuration.
          maxLength: 256
          minLength: 0
        occurrence:
          $ref: '#/components/schemas/Occurrence'
        paused:
          type: boolean
          description: Boolean flag to determine if the Maintenance Window configuration is paused or still live.
        query:
          type: string
          description: Dynamic Focus Query that determines the scope of the Maintenance Window configuration.
          maxLength: 2048
          minLength: 0
        retriggerOpenAlertsEnabled:
          type: boolean
          description: Boolean flag to determine if we should retrigger open alerts to be sent out for any events that opened during this maintenance window, and continues to remain open after the window expires
        scheduling:
          $ref: '#/components/schemas/MaintenanceConfigScheduling'
        state:
          type: string
          description: 'State of the Maintenance Window, it can be: UNSCHEDULED, SCHEDULED, ACTIVE, PAUSED, EXPIRED.'
          enum:
          - UNSCHEDULED
          - SCHEDULED
          - ACTIVE
          - PAUSED
          - EXPIRED
        tagFilterExpression:
          $ref: '#/components/schemas/TagFilterExpressionElement'
        tagFilterExpressionEnabled:
          type: boolean
          description: Boolean flag to determine if the tagFilterExpression is enabled.
      required:
      - id
      - name
      - occurrence
      - query
      - scheduling
    MaintenanceWindow:
      type: object
      description: A set of time periods when the Maintenance Window Configuration is active.
      properties:
        end:
          type: integer
          format: int64
          minimum: 1
        id:
          type: string
          maxLength: 64
          minLength: 0
        start:
          type: integer
          format: int64
          minimum: 0
      required:
      - id
    MaintenanceConfigScheduling:
      type: object
      description: Time scheduling of the Maintenance Window configurations.
      discriminator:
        mapping:
          ONE_TIME: '#/components/schemas/OneTimeMaintenanceWindow'
          RECURRENT: '#/components/schemas/RecurrentMaintenanceWindow'
        propertyName: type
      properties:
        duration:
          $ref: '#/components/schemas/Duration'
        start:
          type: integer
          format: int64
          minimum: 1
        type:
          type: string
          maxLength: 2048
          minLength: 0
      required:
      - duration
      - start
      - type
    Duration:
      type: object
      properties:
        amount:
          type: integer
          format: int64
          minimum: 1
        unit:
          type: string
          enum:
          - MINUTES
          - HOURS
          - DAYS
      required:
      - amount
      - unit
    MaintenanceConfigWithLastUpdated:
      type: object
      properties:
        id:
          type: string
          description: ID of the Maintenance Window Configuration.
          maxLength: 64
          minLength: 0
        lastUpdated:
          type: integer
          format: int64
          minimum: 1
        name:
          type: string
          description: Name of the Maintenance Window Configuration.
          maxLength: 256
          minLength: 0
        query:
          type: string
          description: Dynamic Focus Query that determines the scope of the Maintenance Window configuration.
          maxLength: 2048
          minLength: 0
        windows:
          type: array
          description: A set of time periods when the Maintenance Window Configuration is active.
          items:
            $ref: '#/components/schemas/MaintenanceWindow'
          maxItems: 1
          minItems: 0
          uniqueItems: true
      required:
      - id
      - name
      - query
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: authorization
      type: apiKey
      description: "## Example\n\n```bash\ncurl --request GET \\\n  --url https://test-instana.instana.io/api/application-monitoring/catalog/metrics \\\n  --header 'authorization: apiToken xxxxxxxxxxxxxxxx'\n```\n"
x-tagGroups:
- name: Websites & Mobile Apps
  tags:
  - Website Metrics
  - Website Catalog
  - Website Analyze
  - Website Configuration
  - Mobile App Metrics
  - Mobile App Catalog
  - Mobile App Analyze
  - Mobile App Configuration
  - End User Monitoring
- name: Applications
  tags:
  - Application Metrics
  - Application Resources
  - Application Catalog
  - Application Analyze
  - Application Settings
  - Application Topology
  - Application Alert Configuration
  - Global Application Alert Configuration
- name: Infrastructure
  tags:
  - Infrastructure Analyze
  - Infrastructure Metrics
  - Infrastructure Resources
  - Infrastructure Catalog
  - Infrastructure Topology
- name: Logging
  tags:
  - Logging Analyze
- name: Synthetic Monitoring
  tags:
  - Synthetic Catalog
  - Synthetic Metrics
  - Synthetic Settings
  - Synthetic Test Playback Results
  - Synthetic Alert Configuration
- name: Logs
  tags:
  - Log Alert Configuration
- name: Events
  tags:
  - Events
  - Event Settings
- name: Automation
  tags:
  - Action Catalog
  - Action History
  - Policies
- name: Service Levels
  tags:
  - SLI Settings
  - SLI Report
  - Apdex Settings
  - Apdex Report
  - Service Levels Objective(SLO) Configurations
  - Service Levels Objective(SLO) Report
  - Service Levels Alert Configuration
  - SLO Correction Configurations
  - SLO Correction Windows
- name: AI Management
  tags:
  - AI Management
- name: Settings
  tags:
  - Custom Dashboards
  - User
  - Groups
  - Teams
  - Roles
  - Audit Log
  - API Token
  - Maintenance Configuration
  - Synthetic Calls
  - Session Settings
  - Automation Settings
  - Authentication
- name: Open Beta Features
  tags:
  - Infrastructure Analyze
- name: Closed Beta Features
  tags:
  - Infrastructure Alert Configuration
- name: Instana
  tags:
  - Releases
  - Host Agent
  - Health
  - Usage
